// GENERATED by web/tools/split.mjs from tools/monolith.html -- do not edit during G1c.
import { apicall } from '../core/api.js';
import { showToast } from '../core/util.js';
import { loadAgents } from './attack-path.js';
import { _openAgentActionModal } from './integrations.js';


// ── Stop Agent ───────────────────────────────────────────────────────────────
var _stopAgentTargetId = null;

export function openStopAgentModal(agentId, hostname) {
  _stopAgentTargetId = agentId;
  _openAgentActionModal(hostname, 'stop-agent');
}

export function closeStopAgentModal() {
  document.getElementById('stop-agent-overlay').classList.remove('open');
}

export function submitStopAgent() {
  if (!_stopAgentTargetId) return;
  var reason = document.getElementById('stop-agent-reason').value.trim();
  if (!reason) { showToast('Reason is required', 'err'); return; }
  if (!confirm('Stop agent permanently?\n\nReason: ' + reason + '\n\nThis cannot be undone remotely. Proceed?')) return;

  var btn = document.getElementById('stop-agent-submit-btn');
  btn.disabled = true;
  apicall('/api/agents/' + encodeURIComponent(_stopAgentTargetId) + '/stop', {
    method: 'POST',
    body: JSON.stringify({ reason: reason })
  }).then(function() {
    btn.disabled = false;
    showToast('Stop dispatched', 'ok');
    closeStopAgentModal();
    loadAgents();
  }).catch(function(e) { btn.disabled = false; showToast(e.message, 'err'); });
}

// ── Uninstall Agent ──────────────────────────────────────────────────────
// Verified uninstall: requires a live connection, waits for the endpoint to
// confirm before the record changes -- unlike Force Remove below, this
// never silently claims an unreachable endpoint is gone.
var _uninstallAgentTargetId = null;

export function openUninstallAgentModal(agentId, hostname) {
  _uninstallAgentTargetId = agentId;
  _openAgentActionModal(hostname, 'uninstall-agent');
}

export function closeUninstallAgentModal() {
  document.getElementById('uninstall-agent-overlay').classList.remove('open');
}

export function submitUninstallAgent() {
  if (!_uninstallAgentTargetId) return;
  var reason = document.getElementById('uninstall-agent-reason').value.trim();
  if (!reason) { showToast('Reason is required', 'err'); return; }
  if (!confirm('Uninstall this agent from the endpoint?\n\nReason: ' + reason + '\n\nThe agent must be online to confirm. Proceed?')) return;

  var btn = document.getElementById('uninstall-agent-submit-btn');
  btn.disabled = true;
  apicall('/api/agents/' + encodeURIComponent(_uninstallAgentTargetId) + '/uninstall', {
    method: 'POST',
    body: JSON.stringify({ reason: reason })
  }).then(function(res) {
    btn.disabled = false;
    if (res && res.error) { showToast(res.error, 'err'); return; }
    showToast('Uninstall dispatched', 'ok');
    closeUninstallAgentModal();
    loadAgents();
  }).catch(function(e) { btn.disabled = false; showToast(e.message, 'err'); });
}

// ── Remove Agent (Force Remove) ─────────────────────────────────────────────
// Removes the dashboard record only (sets state=retired) -- unlike Stop
// Agent, this never talks to the endpoint and works regardless of whether
// the agent is currently connected.
var _removeAgentTargetId = null;

export function openRemoveAgentModal(agentId, hostname) {
  _removeAgentTargetId = agentId;
  _openAgentActionModal(hostname, 'remove-agent');
}

export function closeRemoveAgentModal() {
  document.getElementById('remove-agent-overlay').classList.remove('open');
}

export function submitRemoveAgent() {
  if (!_removeAgentTargetId) return;
  var reason = document.getElementById('remove-agent-reason').value.trim();
  if (!reason) { showToast('Reason is required', 'err'); return; }
  if (!confirm('Remove this agent from the dashboard?\n\nReason: ' + reason + '\n\nThe agent software on the endpoint keeps running -- this only removes the record here. Proceed?')) return;

  var btn = document.getElementById('remove-agent-submit-btn');
  btn.disabled = true;
  apicall('/api/agents/' + encodeURIComponent(_removeAgentTargetId) + '/remove', {
    method: 'POST',
    body: JSON.stringify({ reason: reason })
  }).then(function() {
    btn.disabled = false;
    showToast('Agent removed', 'ok');
    closeRemoveAgentModal();
    loadAgents();
  }).catch(function(e) { btn.disabled = false; showToast(e.message, 'err'); });
}

export function triggerTicketingSync() {
  apicall('/api/ticketing/sync', { method: 'POST' })
    .then(function() { showToast('Sync started', 'ok'); })
    .catch(function(e) { showToast(e.message, 'err'); });
}