// GENERATED by web/tools/split.mjs from tools/monolith.html -- do not edit during G1c.
import { state } from '../core/state.js';
import { apicall } from '../core/api.js';
import { x } from '../core/escape.js';
import { showToast } from '../core/util.js';
import { campaignDisplayStatus } from './campaigns.js';
import { showTab } from './shell.js';
import { loadComplianceReport } from '../legacy.js';


// ── Compliance score tiles ─────────────────────────────────────────────────
// Renders one tile per compliance framework. Scores come from the
// /api/compliance/scores endpoint which reads compliance_snapshots (O(1)).
// Called fleet-wide (no agentId) so the dashboard shows the worst-case posture
// across all enrolled agents — the view a CISO cares about.
export function loadComplianceScores(agentId) {
  var url = '/api/compliance/scores' + (agentId ? '?agentId=' + encodeURIComponent(agentId) : '');
  apicall(url).then(function(scores) {
    var el = document.getElementById('compliance-tiles');
    if (!el) return;
    if (!scores || !scores.length) {
      el.innerHTML = '<div style="color:var(--muted);font-size:0.78rem;padding:0.4rem 0">No compliance data yet — run a scenario to generate scores.</div>';
      return;
    }
    el.innerHTML = scores.map(complianceTile).join('');
  }).catch(function() {});
}

function complianceWhy(fw) {
  var tested = fw.testedControls || 0;
  if (tested === 0) return 'No controls tested yet — run a scenario to generate compliance evidence.';
  var pct = Math.round(fw.compliancePct || 0);
  var passing = fw.passingControls || 0;
  var failing = fw.failingControls || 0;
  var untested = fw.untestedControls != null ? fw.untestedControls : 0;
  if (fw.enrolledAgentCount > 1) {
    return pct + '% compliant — worst of ' + fw.enrolledAgentCount + ' enrolled endpoints. Click for full breakdown.';
  }
  return pct + '% compliant — ' + passing + ' of ' + tested + ' tested controls passing, ' +
    failing + ' failing, ' + untested + ' untested.';
}

function openComplianceDetail(frameworkId, agentId) {
  showTab('compliance');
  var fwSel = document.getElementById('cmp-fw-sel');
  var agSel = document.getElementById('cmp-agent-sel');
  if (fwSel) fwSel.value = frameworkId;
  if (agSel && agentId) agSel.value = agentId;
  loadComplianceReport();
}

function complianceTile(fw) {
  var pct     = fw.compliancePct  || 0;
  var cov     = fw.coveragePct    || 0;
  var tested  = fw.testedControls || 0;
  var passing = fw.passingControls || 0;
  var failing = fw.failingControls || 0;
  var untested = fw.untestedControls != null ? fw.untestedControls : (fw.testableControls - tested);
  var hasData  = tested > 0;

  var scoreColor  = !hasData ? 'var(--muted)'
                  : pct >= 75 ? 'var(--success)'
                  : pct >= 50 ? 'var(--warning)'
                  : 'var(--danger)';
  var borderColor = !hasData ? 'var(--border)'
                  : pct >= 75 ? 'var(--success)'
                  : pct >= 50 ? 'var(--warning)'
                  : 'var(--danger)';
  var covColor    = cov >= 80 ? 'var(--teal)' : cov >= 50 ? 'var(--warning)' : 'var(--danger)';

  var scoreStr = hasData ? Math.round(pct) + '%' : '—';
  var subLine  = hasData
    ? passing + ' pass &middot; ' + failing + ' fail &middot; ' + untested + ' untested'
    : 'No runs yet';

  // A control needs every mapped test to pass to count as compliant — one
  // bypass found among many blocked attempts still fails the whole control.
  // Without this note, a low % here (especially mid variant-sweep, where
  // finding bypasses is the point) reads as "everything is broken" rather
  // than "gating is strict — see the Controls table for the real pass rate."
  var gatingNote = (hasData && failing > 0)
    ? '<div style="font-size:0.6rem;color:var(--muted);margin-top:0.2rem;font-style:italic">Any 1 failed test fails the control — see breakdown</div>'
    : '';

  // Compliance % is only computed over TESTED controls (passing/tested) --
  // untested controls are excluded from the denominator entirely, not
  // counted against you. A high % from a narrow slice of testable controls
  // doesn't mean the framework is broadly satisfied; it means the controls
  // you've actually run are passing. Flag it when coverage itself is thin.
  var lowCoverageNote = (hasData && cov < 50)
    ? '<div style="font-size:0.6rem;color:var(--muted);margin-top:0.2rem;font-style:italic">Only ' + Math.round(cov) + '% of testable controls covered — untested controls aren\'t reflected in this %</div>'
    : '';

  var covBar = hasData
    ? '<div style="margin-top:0.5rem">' +
        '<div style="background:var(--border);border-radius:2px;height:3px;overflow:hidden">' +
          '<div style="height:3px;width:' + Math.round(cov) + '%;background:' + covColor +
               ';border-radius:2px;transition:width 0.4s ease"></div>' +
        '</div>' +
        '<div style="font-size:0.63rem;color:var(--muted);margin-top:0.2rem">' + Math.round(cov) + '% coverage</div>' +
      '</div>'
    : '';

  return '<div class="kpi-card stat-tile" ' +
    'style="border-left:3px solid ' + borderColor + ';cursor:pointer;min-width:155px;max-width:220px" ' +
    'onclick="openComplianceDetail(\'' + x(fw.frameworkId) + '\', \'' + x(fw.agentId) + '\')" ' +
    'title="' + x(fw.frameworkName) + '\n' + x(complianceWhy(fw)) + '">' +
    '<div class="stat-top">' +
      '<div style="flex:1;min-width:0">' +
        '<div class="kpi-label" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + x(fw.shortName) + '</div>' +
        '<div class="kpi-value" style="font-size:1.6rem;line-height:1.1;color:' + scoreColor + '">' + scoreStr + '</div>' +
      '</div>' +
      '<div style="font-size:0.62rem;text-align:right;color:var(--muted);line-height:1.5;flex-shrink:0;margin-left:0.5rem">' +
        '<div class="u-fw600">' + x(fw.regulator) + '</div>' +
        (hasData ? '<div>' + fw.totalControls + ' controls</div>' : '') +
      '</div>' +
    '</div>' +
    covBar +
    '<div class="kpi-sub" style="font-size:0.66rem;margin-top:0.3rem;line-height:1.4">' + subLine + '</div>' +
    gatingNote +
    lowCoverageNote +
    '</div>';
}

// refreshDashboardCampaigns — standalone fn so it can be called from the WS
// handler and the periodic poll without running the full dashboard reload.

export function refreshDashboardCampaigns() {
  apicall('/api/campaigns').then(function(cs) {
    // KPI tile — Active campaigns (running now).
    var running = (cs || []).filter(function(c) { return c.summary && c.summary.status === 'running'; }).length;
    var cvEl = document.getElementById('kpi-campaigns-val');
    if (cvEl) {
      cvEl.textContent = running;
      document.getElementById('kpi-campaigns-sub').textContent = running ? 'running now' : 'none running';
      // Update both dots: blink+accent when active, solid grey when idle
      var kpiDot = document.getElementById('kpi-campaigns-dot');
      var panelDot = document.getElementById('dash-campaigns-dot');
      if (running) {
        [kpiDot, panelDot].forEach(function(d) { if (d) { d.className = 'dot-live'; d.removeAttribute('style'); } });
      } else {
        [kpiDot, panelDot].forEach(function(d) { if (d) { d.className = ''; d.style.cssText = 'display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--muted);vertical-align:middle;flex-shrink:0;'; } });
      }
    }
    // Live campaigns panel.
    var el = document.getElementById('dash-campaigns');
    if (!el) return;
    var liveList = (cs || []).filter(function(c) { return c.summary && c.summary.status === 'running'; });
    if (!liveList.length) { el.innerHTML = '<div class="empty" style="padding:1.5rem">No campaigns running.</div>'; return; }
    el.innerHTML = liveList.map(function(c) {
      var s = c.summary || {};
      var cds = campaignDisplayStatus(s);
      return '<div class="lrow u-pointer" onclick="openCampaignDetail(\'' + x(c.id) + '\')">' +
        '<div class="lic" style="color:var(--accent);background:rgba(47,129,247,0.1)"><svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M1 8h3l2-5 4 10 2-5h3"/></svg></div>' +
        '<div class="lmain"><div class="lt">' + x(c.name) + ' <span class="sbadge s-' + cds.cls + '">' + x(cds.label) + '</span></div>' +
          '<div class="ls">' + x(c.scenarioName || '') + ' · ' + (s.dispatched || 0) + '/' + (s.targets || 0) + ' agents</div>' +
          '<div class="prog"><i style="width:' + (s.progress || 0) + '%"></i></div></div>' +
        '<div class="lr"><div style="font-family:var(--font-display);font-size:1rem;font-weight:700">' + (s.progress || 0) + '%</div></div></div>';
    }).join('');
  }).catch(function() {});
}

export function openChangePassword() {
  state._pwForced = false;
  document.getElementById('changepw-title').textContent = 'Change Password';
  document.getElementById('changepw-sub').textContent = 'Update your account password.';
  document.getElementById('cpw-cancel-btn').style.display = '';
  document.getElementById('cpw-current').value = '';
  document.getElementById('cpw-new').value = '';
  document.getElementById('cpw-confirm').value = '';
  document.getElementById('cpw-err').textContent = '';
  document.getElementById('changepw-overlay').classList.add('open');
}
export function closeChangePassword() {
  if (state._pwForced) return;
  document.getElementById('changepw-overlay').classList.remove('open');
}
export function submitChangePassword() {
  var current = document.getElementById('cpw-current').value;
  var newpw   = document.getElementById('cpw-new').value;
  var confirm = document.getElementById('cpw-confirm').value;
  document.getElementById('cpw-err').textContent = '';
  if (!current || !newpw) { document.getElementById('cpw-err').textContent = 'All fields are required.'; return; }
  if (newpw !== confirm)  { document.getElementById('cpw-err').textContent = 'New passwords do not match.'; return; }
  if (newpw.length < 8)   { document.getElementById('cpw-err').textContent = 'Password must be at least 8 characters.'; return; }
  apicall('/api/auth/change-password', { method: 'POST', body: JSON.stringify({ currentPassword: current, newPassword: newpw }) })
  .then(function(res) {
    if (res.error) throw new Error(res.error);
    state._pwForced = false;
    document.getElementById('changepw-overlay').classList.remove('open');
    showToast('Password updated successfully', 'ok');
  })
  .catch(function(e) { document.getElementById('cpw-err').textContent = e.message; });
}

/* ═══════════════════════════════════════════════════════════════════════════
   THREAT-INTEL CONNECTOR
   ═══════════════════════════════════════════════════════════════════════════ */

export function loadCalderaStatus() {
  var wrap = document.getElementById('caldera-status-wrap');
  if (wrap) wrap.style.display = '';
  var btn = document.getElementById('caldera-check-btn');
  if (btn) btn.disabled = true;

  apicall('/api/caldera/status').then(function(d) {
    var dot;
    if (d.reachable) {
      dot = '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--success);margin-right:6px;vertical-align:middle"></span><span class="u-success">Connected</span>';
    } else if (d.httpStatus === 401) {
      dot = '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--warning);margin-right:6px;vertical-align:middle"></span><span class="u-warning">Auth Error — wrong API key</span>';
    } else {
      dot = '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--danger);margin-right:6px;vertical-align:middle"></span><span class="u-danger">Unreachable</span>';
    }
    document.getElementById('cs-caldera-status').innerHTML = dot;
    document.getElementById('cs-caldera-url').textContent = d.url || '(not configured)';
    document.getElementById('cs-caldera-version').textContent = d.version || (d.reachable ? 'unknown' : '—');
    if (d.reachable) {
      var abLabel = d.abilityCount.toLocaleString() + ' abilities';
      if (d.byPlugin) {
        var parts = Object.keys(d.byPlugin).sort().map(function(k) { return k + ': ' + d.byPlugin[k].toLocaleString(); });
        abLabel += ' (' + parts.join(', ') + ')';
      }
      if (d.uniqueTechniques) abLabel += ' · ' + d.uniqueTechniques + ' unique techniques';
      abLabel += ' · ' + (d.adversaryCount || 0) + ' adversary profiles';
      document.getElementById('cs-caldera-abilities').textContent = abLabel;
    } else {
      document.getElementById('cs-caldera-abilities').textContent = '—';
    }
    document.getElementById('cs-caldera-latency').textContent = d.reachable ? (d.latencyMs + ' ms') : '—';
    var errEl = document.getElementById('cs-caldera-error');
    if (d.error) {
      errEl.textContent = d.error;
      errEl.style.display = '';
    } else {
      errEl.style.display = 'none';
    }
  }).catch(function(e) {
    var errEl = document.getElementById('cs-caldera-error');
    if (errEl) { errEl.textContent = e.message; errEl.style.display = ''; }
    document.getElementById('cs-caldera-status').innerHTML =
      '<span class="u-danger">Error checking status</span>';
  }).finally(function() {
    if (btn) btn.disabled = false;
  });
}

// _renderConnectorCard fills one per-connector card (MISP/OpenCTI) from its
// ConnectorStatus.BySource entry. rawCountElId differs per connector because
// the two label their raw fetch count differently ("Events" for MISP vs
// "Threat Actor Nodes" for OpenCTI) — they're genuinely different kinds of
// raw data, not the same concept under two names. See
// docs/superpowers/specs/2026-07-22-connector-rich-status-cards-design.md.
export function _renderConnectorCard(prefix, enabled, stat, rawCountElId) {
  var statusEl = document.getElementById('cs-' + prefix + '-status');
  if (!enabled) {
    statusEl.textContent = '✗ Not configured';
    statusEl.style.color = 'var(--muted)';
  } else if (stat && stat.error) {
    statusEl.textContent = '⚠ Error';
    statusEl.style.color = '#f85149';
  } else {
    statusEl.textContent = '✓ Connected';
    statusEl.style.color = '#5cead8';
  }
  document.getElementById(rawCountElId).textContent = stat ? stat.rawCount.toLocaleString() : '—';
  document.getElementById('cs-' + prefix + '-actors').textContent = stat ? stat.actorCount.toLocaleString() : '—';
  document.getElementById('cs-' + prefix + '-lastfetch').textContent = (stat && stat.fetchedAt) ? new Date(stat.fetchedAt).toLocaleString() : '—';
  var errEl = document.getElementById('cs-' + prefix + '-error');
  if (stat && stat.error) { errEl.textContent = stat.error; errEl.style.display = ''; }
  else { errEl.style.display = 'none'; }
}

// ── Generic config-save confirmation ────────────────────────────────────────
// Shared by every "Save" that can silently overwrite a previously-saved
// connector/config value (threat intel, OpenAEV, ITSM ticketing connectors).
// Each caller builds its own diff HTML (via _diffRow/_diffSecretRow below)
// and passes a zero-arg onConfirm that performs the actual save.
var CONFIRM_DIFF_PENDING = null; // onConfirm callback awaiting the modal's Save click

export function openConfirmDiffModal(title, diffHtml, onConfirm) {
  document.getElementById('confirm-diff-title').textContent = title;
  document.getElementById('confirm-diff-body').innerHTML = diffHtml;
  CONFIRM_DIFF_PENDING = onConfirm;
  document.getElementById('confirm-diff-overlay').classList.add('open');
}

export function closeConfirmDiffModal() {
  document.getElementById('confirm-diff-overlay').classList.remove('open');
  CONFIRM_DIFF_PENDING = null;
}

export function runConfirmDiffModal() {
  var onConfirm = CONFIRM_DIFF_PENDING;
  document.getElementById('confirm-diff-overlay').classList.remove('open');
  CONFIRM_DIFF_PENDING = null;
  if (onConfirm) onConfirm();
}

// Old-value-struck-through / new-value-highlighted row for a plain field.
export function _diffRow(label, oldVal, newVal) {
  return '<div class="tiny" style="margin-bottom:0.4rem"><span class="muted">' + x(label) + ':</span><br>' +
    '<span style="color:var(--danger);text-decoration:line-through">' + x(oldVal || '(empty)') + '</span><br>' +
    '<span class="u-success">' + x(newVal || '(empty)') + '</span></div>';
}

// A secret/password field never round-trips its real value to the browser, so it
// can only ever say whether it will change, never show old/new text.
export function _diffSecretRow(label, changed) {
  return '<div class="tiny" style="margin-bottom:0.4rem"><span class="muted">' + x(label) + ':</span> ' +
    (changed ? '<span class="u-warning">will be replaced</span>' : '<span class="muted">unchanged (kept)</span>') + '</div>';
}