// GENERATED by web/tools/split.mjs from tools/monolith.html -- do not edit during G1c.
import { state } from '../core/state.js';
import { apicall } from '../core/api.js';
import { x } from '../core/escape.js';
import { ago, showToast } from '../core/util.js';
import { agentGroupTree, gpFlattenGroups, resolveGroupTargetAgents, scenarioCategoryOf } from './attack-path.js';
import { ROLE, _riskScoreColor, showTab } from './shell.js';
import { _vexAllTechniques, _vexAvailableVariants, _vexCalderaTechniques, _vexDispatchFullSweep, filterVexTechniqueList } from './variants.js';
import { loadRuns, openModal, sweepStatusLabel, verdictBadge, verdictCounts } from '../legacy.js';


// ── Endpoint Mastery ──────────────────────────────────────────────────────────

var EM_CATALOG = [
  { id:'em-01-control-validation',     num:'01', name:'Control Validation',        desc:'EDR/AV presence, tamper protection, real-time enforcement' },
  { id:'em-02-attack-behavioral-depth',num:'02', name:'Behavioral Depth',          desc:'PowerShell variant matrix — encoded, obfuscated, AMSI, reflective' },
  { id:'em-03-memory-attacks',         num:'03', name:'Memory-Based Attacks',      desc:'LSASS handle, cross-process R/W, process hollowing precursor' },
  { id:'em-04-credential-theft',       num:'04', name:'Credential Theft',          desc:'LSASS, SAM hive, DPAPI master key accessibility' },
  { id:'em-05-persistence-validation', num:'05', name:'Persistence Validation',    desc:'Run keys, startup folder, scheduled task mutations' },
  { id:'em-06-defense-evasion',        num:'06', name:'Defense Evasion',           desc:'LOLBin proxy execution, structural bypasses' },
  { id:'em-07-ransomware-readiness',   num:'07', name:'Ransomware Readiness',      desc:'Full kill chain — canary XOR, shadow copy, backup destruction' },
  { id:'em-08-exploit-mitigation',     num:'08', name:'Exploit Mitigation',        desc:'DEP, ASLR, SEHOP configuration posture' },
  { id:'em-09-browser-attack',         num:'09', name:'Browser Attack',            desc:'Credential store / cookie directory isolation' },
  { id:'em-10-endpoint-exfiltration',  num:'10', name:'Exfiltration Channels',     desc:'DNS / egress channel boundary monitoring' },
  { id:'em-11-hardening-validation',   num:'11', name:'Hardening Validation',      desc:'LAPS, Credential Guard, kernel integrity features' },
  { id:'em-12-adversary-emulation',    num:'12', name:'Adversary Emulation',       desc:'APT29 profile — recon + discovery operational signatures' },
  { id:'em-13-product-validation',     num:'13', name:'Product Health',            desc:'Security product process / driver / self-defense audit' },
  { id:'em-14-continuous-validation',  num:'14', name:'Posture Drift Engine',      desc:'Continuous differential validation against control baseline' }
];

export function loadEmTab() {
  Promise.all([apicall('/api/scenarios/runs'), apicall('/api/agents')])
  .then(function(res) {
    var runs = res[0] || [];
    var agentList = res[1] || [];

    // Build map: scenarioId → most-recent run with results
    var lastRunMap = {};
    runs.forEach(function(r) {
      var sid = r.scenarioId;
      if (!sid || EM_CATALOG.every(function(e) { return e.id !== sid; })) return;
      if (!lastRunMap[sid] && (r.results || []).length) lastRunMap[sid] = r;
    });

    // Overall summary stats
    var layersRun = 0, layersPass = 0, layersFail = 0, totalPass = 0, totalFail = 0;
    EM_CATALOG.forEach(function(e) {
      var r = lastRunMap[e.id];
      if (!r) return;
      layersRun++;
      var p = 0, f = 0;
      (r.results || []).forEach(function(c) {
        if (c.result === 'pass' || c.result === 'blocked') p++;
        else if (c.result === 'fail') f++;
      });
      totalPass += p; totalFail += f;
      if (p + f > 0 && Math.round(p / (p + f) * 100) >= 60) layersPass++; else if (p + f > 0) layersFail++;
    });

    var summaryEl = document.getElementById('em-summary');
    var badgeEl   = document.getElementById('em-summary-badge');
    if (badgeEl) badgeEl.textContent = layersRun + ' / 14 layers run';

    if (summaryEl) {
      if (!layersRun) {
        summaryEl.innerHTML = '<div class="empty" style="padding:0.5rem">Run one or more EM scenarios to generate coverage data.</div>';
      } else {
        var overallPct = (totalPass + totalFail) ? Math.round(totalPass / (totalPass + totalFail) * 100) : 0;
        var col = _riskScoreColor(overallPct);
        summaryEl.innerHTML =
          '<div style="display:flex;align-items:center;gap:2rem;flex-wrap:wrap">' +
            emSummaryBig(overallPct + '%', 'Overall Score', col) +
            emSummaryBig(layersRun + '/14', 'Layers Run', 'var(--text)') +
            emSummaryBig(layersPass + '', 'Layers Passing', 'var(--success)') +
            emSummaryBig(layersFail + '', 'Layers Failing', layersFail ? 'var(--danger)' : 'var(--muted)') +
            emSummaryBig((14 - layersRun) + '', 'Not Yet Run', 'var(--muted)') +
          '</div>' +
          '<div style="margin-top:0.75rem;height:6px;background:var(--elevated);border-radius:3px;overflow:hidden">' +
            '<div style="height:100%;width:' + Math.round(layersRun / 14 * 100) + '%;background:' + col + ';border-radius:3px;transition:width .6s ease"></div>' +
          '</div>' +
          '<div style="font-size:0.7rem;color:var(--muted);margin-top:0.3rem">' + Math.round(layersRun / 14 * 100) + '% of Endpoint Mastery layers exercised</div>';
      }
    }

    // Layer cards
    var gridEl = document.getElementById('em-grid');
    if (!gridEl) return;
    gridEl.innerHTML = EM_CATALOG.map(function(e) {
      var run = lastRunMap[e.id];
      var p = 0, f = 0;
      if (run) {
        (run.results || []).forEach(function(c) {
          if (c.result === 'pass' || c.result === 'blocked') p++;
          else if (c.result === 'fail') f++;
        });
      }
      var pct = (p + f) ? Math.round(p / (p + f) * 100) : null;
      var col = pct === null ? 'var(--muted)' : _riskScoreColor(pct);
      // A completed run with zero pass/fail (every step errored — e.g. the agent
      // couldn't even launch the process) is NOT the same as "never run": it has
      // a real timestamp and a real report. Only fall back to "Not run" when
      // there's no run record at all.
      var statusHtml = pct !== null
        ? '<span class="sbadge" style="background:' + (pct >= 80 ? 'rgba(35,134,54,0.15)' : pct >= 50 ? 'rgba(210,153,34,0.15)' : 'rgba(218,54,51,0.15)') + ';color:' + col + '">' + pct + '% pass</span>'
        : run
          ? '<span class="sbadge" style="background:rgba(218,54,51,0.15);color:var(--danger)">Error</span>'
          : '<span class="sbadge" style="background:var(--elevated);color:var(--muted)">Not run</span>';
      var runTs = run ? '<div style="font-size:0.68rem;color:var(--muted);margin-top:0.3rem">Last: ' + ago(run.completedAt || run.startedAt) + (run.agentId ? ' · ' + x(run.agentId) : '') + '</div>' : '';
      var barHtml = pct !== null
        ? '<div style="height:3px;background:var(--elevated);border-radius:2px;margin:0.5rem 0 0;overflow:hidden"><div style="height:100%;width:' + pct + '%;background:' + col + ';border-radius:2px"></div></div>'
        : '';
      var canRun = agentList.length > 0;
      return '<div class="dash-panel" style="padding:0">' +
        '<div style="display:flex;align-items:flex-start;gap:0.75rem;padding:0.85rem 1rem">' +
          '<div style="flex-shrink:0;width:36px;height:36px;border-radius:8px;background:rgba(47,129,247,0.12);color:var(--accent);display:flex;align-items:center;justify-content:center;font-family:var(--font-mono);font-size:0.75rem;font-weight:700">' + x(e.num) + '</div>' +
          '<div style="flex:1;min-width:0">' +
            '<div style="display:flex;align-items:center;justify-content:space-between;gap:0.5rem;flex-wrap:wrap">' +
              '<span style="font-weight:600;font-size:0.9rem;color:var(--text)">' + x(e.name) + '</span>' +
              statusHtml +
            '</div>' +
            '<div style="font-size:0.75rem;color:var(--muted);margin-top:0.25rem;line-height:1.4">' + x(e.desc) + '</div>' +
            barHtml +
            runTs +
          '</div>' +
        '</div>' +
        '<div style="border-top:1px solid var(--border);padding:0.5rem 1rem;display:flex;gap:0.5rem;align-items:center">' +
          (run ? '<a style="font-size:0.75rem;color:var(--accent);cursor:pointer" onclick=\'viewRunResults(' + JSON.stringify(run).replace(/'/g,"&#39;") + ')\'>View report →</a>' : '') +
          '<span class="u-flex1"></span>' +
          ((ROLE === 'admin' || ROLE === 'analyst') ? '<button class="btn btn-outline btn-sm" style="font-size:0.72rem;padding:0.2rem 0.6rem" onclick="cloneScenario(\'' + x(e.id) + '\')" title="Clone into an editable custom scenario">&#9112; Clone</button>' : '') +
          (canRun ? '<button class="btn btn-outline btn-sm" style="font-size:0.72rem;padding:0.2rem 0.6rem" onclick="emRunLayer(\'' + x(e.id) + '\')" title="Run this layer">&#9654; Run</button>' : '') +
        '</div>' +
      '</div>';
    }).join('');
  })
  .catch(function(e) { showToast('Endpoint Mastery load failed: ' + e.message, 'err'); });
}

function emSummaryBig(val, label, col) {
  return '<div style="text-align:center;min-width:80px">' +
    '<div style="font-size:1.5rem;font-weight:700;line-height:1;color:' + col + '">' + val + '</div>' +
    '<div style="font-size:0.68rem;color:var(--muted);margin-top:0.2rem;text-transform:uppercase;letter-spacing:0.04em">' + label + '</div>' +
  '</div>';
}

export function emRunLayer(scenarioId) {
  if (!state.agents.length) { showToast('No agents enrolled.', 'err'); showTab('agents'); return; }
  openModal(scenarioId, state.agents[0].agentId);
}

// ── Endpoint Mastery Full Sweep ─────────────────────────────────────────
// Own target-mode state, deliberately not shared with _vexTargetMode/
// _vexGroupSel -- see design spec's "duplicate and adapt, don't share"
// decision (docs/superpowers/specs/2026-08-13-em-full-sweep-design.md).
var _emTargetMode = 'individual';


export function openEMSweepModal() {
  if (!state.agents.length) { showToast('No agents enrolled.', 'err'); showTab('agents'); return; }
  _emTargetMode = 'individual';
  state._emGroupSel = {};
  document.querySelector('input[name="em-sweep-target-mode"][value="individual"]').checked = true;
  document.getElementById('em-sweep-individual-wrap').style.display = '';
  document.getElementById('em-sweep-group-wrap').style.display = 'none';
  var sel = document.getElementById('em-sweep-agent');
  sel.innerHTML = state.agents.map(function(a) {
    return '<option value="' + x(a.agentId) + '">' + x(a.agentId) + ' — ' + x(a.hostname) + '</option>';
  }).join('');
  renderEMSweepGroupList(); // agentGroupTree is already loaded at boot by loadAgentGroupTree() -- no fresh fetch needed
  document.getElementById('em-sweep-modal-overlay').classList.add('open');
}

// renderEMSweepGroupList mirrors renderVexGroupList exactly: gpFlattenGroups
// is the same shared tree-flattening helper the Run Scenario wizard's own
// Group(s) mode and vexRunFullSweep's group mode both already use.
function renderEMSweepGroupList() {
  var list = document.getElementById('em-sweep-group-list');
  if (!list) return;
  var options = gpFlattenGroups(agentGroupTree, 0, null, []);
  if (!options.length) {
    list.innerHTML = '<p class="tiny muted" style="margin:0">No agent groups have been created yet.</p>';
    return;
  }
  list.innerHTML = options.map(function(o) {
    return '<label style="display:flex;align-items:center;gap:0.5rem;padding:0.25rem 0.3rem;cursor:pointer">' +
      '<input type="checkbox" ' + (state._emGroupSel[o.id] ? 'checked' : '') +
      ' onchange="_emGroupSel[' + o.id + ']=this.checked">' +
      '<span style="font-size:0.8rem">' + x(o.label) + '</span></label>';
  }).join('');
}

export function closeEMSweepModal() {
  document.getElementById('em-sweep-modal-overlay').classList.remove('open');
}

export function setEMSweepTargetMode(mode) {
  _emTargetMode = mode;
  document.getElementById('em-sweep-individual-wrap').style.display = mode === 'individual' ? '' : 'none';
  document.getElementById('em-sweep-group-wrap').style.display = mode === 'group' ? '' : 'none';
}

// emResolvedGroupAgents resolves the currently-checked groups to their
// member agents via resolveGroupTargetAgents -- the same pre-existing,
// already-correct helper vexResolvedGroupAgents uses, which recurses into
// subgroups via buildGroupDescendantMap. Do not reimplement group flattening
// here.
function emResolvedGroupAgents() {
  var selectedGroupIds = Object.keys(state._emGroupSel).filter(function(k) { return state._emGroupSel[k]; }).map(Number);
  return resolveGroupTargetAgents(selectedGroupIds);
}

// emSweepDispatch validates the current target selection (the existing
// individual/group/all-agents picker, entirely unchanged) and opens the
// Preview & Confirm overlay -- it no longer dispatches directly. Actual
// dispatch lives solely in _emDispatchFullSweep, called only from the
// preview's Start Full Sweep button.
export function emSweepDispatch() {
  var targets = [];
  if (_emTargetMode === 'individual') {
    var agentId = document.getElementById('em-sweep-agent').value;
    if (!agentId) { showToast('Select an agent', 'err'); return; }
    targets = [agentId];
  } else if (_emTargetMode === 'group') {
    var resolved = emResolvedGroupAgents();
    if (!resolved.length) { showToast('Select at least one group with agents', 'err'); return; }
    targets = resolved.map(function(a) { return a.agentId; });
  } else {
    targets = (state.agents || []).filter(function(a) { return a.status !== 'offline'; }).map(function(a) { return a.agentId; });
    if (!targets.length) { showToast('No online agents', 'err'); return; }
  }

  closeEMSweepModal();
  openSweepPreview('em', { agentIds: targets });
}

// _emDispatchFullSweep is the single source of truth for actually starting
// an EM Full Sweep.
function _emDispatchFullSweep(targets, extraScenarioIds) {
  var agentIds = targets.agentIds;
  var dispatches = agentIds.map(function(agentId) {
    return apicall('/api/em/sweeps', {
      method: 'POST',
      body: JSON.stringify({ agentId: agentId, extraScenarioIds: extraScenarioIds || [] })
    }).then(function(res) {
      if (res && res.error) return { agentId: agentId, ok: false, error: res.error };
      return { agentId: agentId, ok: true };
    }).catch(function(e) {
      return { agentId: agentId, ok: false, error: e.message };
    });
  });

  Promise.all(dispatches).then(function(results) {
    var ok = results.filter(function(r) { return r.ok; });
    var failed = results.filter(function(r) { return !r.ok; });
    if (!failed.length) {
      showToast('Started ' + ok.length + ' EM sweep(s).', 'ok');
    } else if (ok.length) {
      showToast('Started ' + ok.length + '/' + results.length + ' sweeps. Failed: ' +
        failed.map(function(f) { return f.agentId + ' (' + f.error + ')'; }).join(', '), 'err');
    } else {
      showToast('All ' + results.length + ' sweep dispatches failed. ' +
        failed.map(function(f) { return f.agentId + ' (' + f.error + ')'; }).join(', '), 'err');
    }
    if (agentIds.length === 1 && ok.length === 1) {
      apicall('/api/em/sweeps/active?agentId=' + encodeURIComponent(agentIds[0])).then(function(sw) {
        if (sw && sw.id) openEMSweepProgress(sw.id);
      }).catch(function() {});
    } else if (agentIds.length === 1 && failed.length === 1 && /already has a running EM sweep/i.test(failed[0].error || '')) {
      // The 409 conflict means an EM sweep already exists for this agent --
      // possibly one that stalled (e.g. agent_disconnected, never resumed)
      // with zero dispatched runs, so it never appeared anywhere in Live
      // Runs and was otherwise undiscoverable. Rather than leave the
      // operator stuck on a bare error with no path forward, look it up and
      // open its progress drawer directly, which now has a real Cancel
      // Sweep control (renderEMSweepProgress) to actually unblock a new one.
      apicall('/api/em/sweeps/active?agentId=' + encodeURIComponent(agentIds[0])).then(function(sw) {
        if (sw && sw.id) {
          openEMSweepProgress(sw.id);
          showToast('Found the existing sweep blocking this one -- cancel it here to start a new one.', 'err');
        }
      }).catch(function() {});
    }
    showTab('runs');
  });
}

// ── Full Sweep Preview & Confirm ──────────────────────────────────────────
// Shared full-viewport overlay for both Variant and EM Full Sweep. Target
// selection stays entirely in the existing modals (vex-sweep-agent/group
// panel, em-sweep-modal-overlay) -- their final action opens this instead
// of firing confirm()+dispatch directly. Start Full Sweep here calls
// straight into _vexDispatchFullSweep/_emDispatchFullSweep with no further
// confirmation, so those two functions remain the single source of truth
// for actually starting a sweep.
var _sweepPreviewType = null;      // 'variant' | 'em' | null when closed
var _sweepPreviewTargets = null;   // opaque target-info object, passed straight through to the matching dispatch fn
var _vexPreviewExpandedKey = null; // currently expanded "source:techniqueId", or null
var _vexPreviewCache = {};         // "source:techniqueId" -> {loading:bool, error:string, variants:[...]}
var _vexPreviewTactic = '';
var _vexPreviewSearch = '';
// Combined sweep preview shows ART and Caldera as separate collapsible
// sections -- ART starts open (the larger, established source), Caldera
// starts collapsed so a first-time viewer isn't hit with both huge lists
// expanded at once.
var _vexPreviewArtCollapsed = false;
var _vexPreviewCalderaCollapsed = true;
var _emPreviewExpandedId = null;   // currently expanded EM layer id, or null
var _emPreviewCache = {};          // layerId -> {loading:bool, error:string, scenario:{...}}
var _emExtraSelected = {};         // scenarioId -> true, for extra (non-fixed-14) scenarios added to the sweep
var _emExtraSearch = '';

export function openSweepPreview(type, targets) {
  _sweepPreviewType = type;
  _sweepPreviewTargets = targets;
  _vexPreviewExpandedKey = null;
  _emPreviewExpandedId = null;
  // Fresh caches per opening -- a stale generated-variant/scenario list
  // from a previous preview session must never leak into a new one.
  _vexPreviewCache = {};
  _emPreviewCache = {};
  _vexPreviewTactic = '';
  _vexPreviewSearch = '';
  _vexPreviewArtCollapsed = false;
  _vexPreviewCalderaCollapsed = true;
  _emExtraSelected = {};
  _emExtraSearch = '';
  renderSweepPreview();
  document.getElementById('sweep-preview-overlay').classList.add('open');
}

export function closeSweepPreview() {
  document.getElementById('sweep-preview-overlay').classList.remove('open');
  _sweepPreviewType = null;
  _sweepPreviewTargets = null;
}

export function startSweepFromPreview() {
  var type = _sweepPreviewType, targets = _sweepPreviewTargets;
  var extraScenarioIds = Object.keys(_emExtraSelected);
  closeSweepPreview();
  if (type === 'variant') _vexDispatchFullSweep(targets);
  else if (type === 'em') _emDispatchFullSweep(targets, extraScenarioIds);
}

// renderSweepPreview populates the title/summary/filters ONCE per open (or
// on the rare type switch) -- the search input and tactic select it builds
// here are never recreated afterward, only the row list is (see
// _renderVexPreviewList/_renderEMPreviewList), so typing in the search box
// never loses focus or cursor position.
function renderSweepPreview() {
  var titleEl = document.getElementById('sweep-preview-title');
  var summaryEl = document.getElementById('sweep-preview-summary');
  var filtersEl = document.getElementById('sweep-preview-filters');
  if (!titleEl || !summaryEl || !filtersEl) return;

  if (_sweepPreviewType === 'variant') {
    var targets = _sweepPreviewTargets;
    var agentCount = (targets.agents || []).length;
    var artCount = _vexAllTechniques.length;
    var calderaCount = _vexCalderaTechniques.length;
    var variantTotal = _vexAvailableVariants || 0;
    titleEl.textContent = 'Preview & Confirm — Variant Full Sweep';
    summaryEl.textContent = 'Targeting ' + agentCount + ' agent(s). ~' + artCount + ' ART technique(s)' +
      (calderaCount ? ' + ~' + calderaCount + ' Caldera ability/technique(s)' : '') +
      ' dispatched sequentially per agent, ~' + variantTotal.toLocaleString() + '+ individual variants per agent total.';

    var tactics = {};
    _vexAllTechniques.forEach(function(t) { if (t.tactic) tactics[t.tactic] = true; });
    _vexCalderaTechniques.forEach(function(t) { if (t.tactic) tactics[t.tactic] = true; });
    var tacticOpts = '<option value="">All tactics</option>' +
      Object.keys(tactics).sort().map(function(t) {
        return '<option value="' + x(t) + '"' + (t === _vexPreviewTactic ? ' selected' : '') + '>' + x(t) + '</option>';
      }).join('');
    filtersEl.innerHTML =
      '<select onchange="_setVexPreviewTactic(this.value)" class="btn btn-outline btn-sm u-flex1">' + tacticOpts + '</select>' +
      '<input type="text" placeholder="Search T-ID or name…" value="' + x(_vexPreviewSearch) + '" oninput="_setVexPreviewSearch(this.value)" class="btn btn-outline btn-sm u-flex1">';
    _renderVexPreviewList();
  } else if (_sweepPreviewType === 'em') {
    var emTargets = _sweepPreviewTargets;
    var extraCount = Object.keys(_emExtraSelected).length;
    titleEl.textContent = 'Preview & Confirm — Endpoint Mastery Full Sweep';
    summaryEl.textContent = 'Targeting ' + (emTargets.agentIds || []).length + ' agent(s). ' +
      EM_CATALOG.length + ' fixed layers' + (extraCount ? ' + ' + extraCount + ' extra scenario(s)' : '') +
      ' run sequentially per agent.';
    filtersEl.innerHTML = '<input type="text" placeholder="Search extra scenarios to add…" value="' + x(_emExtraSearch) + '" oninput="_setEMExtraSearch(this.value)" class="btn btn-outline btn-sm u-flex1">';
    _renderEMPreviewList();
  }
}

export function _setVexPreviewTactic(v) { _vexPreviewTactic = v; _renderVexPreviewList(); }
export function _setVexPreviewSearch(v) { _vexPreviewSearch = v; _renderVexPreviewList(); }

// _renderVexPreviewList renders two collapsible sections -- ART first, then
// Caldera -- since a combined sweep dispatches every ART technique followed
// by every Caldera ability (see CreateVexSweep). Each section's own
// collapse state is independent (_vexPreviewArtCollapsed/
// _vexPreviewCalderaCollapsed) so a viewer can browse one source without
// wading through the other.
function _renderVexPreviewList() {
  var listEl = document.getElementById('sweep-preview-list');
  var countEl = document.getElementById('sweep-preview-count');
  if (!listEl) return;
  var artFiltered = filterVexTechniqueList(_vexAllTechniques, _vexPreviewTactic, _vexPreviewSearch);
  var calderaFiltered = filterVexTechniqueList(_vexCalderaTechniques, _vexPreviewTactic, _vexPreviewSearch);
  if (countEl) countEl.textContent = artFiltered.length + ' ART, ' + calderaFiltered.length + ' Caldera';
  listEl.innerHTML =
    _renderVexPreviewSection('art', 'ART', artFiltered, _vexPreviewArtCollapsed) +
    _renderVexPreviewSection('caldera', 'Caldera', calderaFiltered, _vexPreviewCalderaCollapsed);
}

function _renderVexPreviewSection(source, label, filtered, collapsed) {
  var header = '<div style="display:flex;align-items:center;gap:0.5rem;padding:0.5rem 0.6rem;cursor:pointer;background:var(--elevated);border-bottom:1px solid var(--border)" onclick="_toggleVexPreviewSection(\'' + source + '\')">' +
      '<span style="width:12px;flex-shrink:0;color:var(--muted);font-size:0.7rem">' + (collapsed ? '&#9656;' : '&#9662;') + '</span>' +
      '<span style="font-weight:600;font-size:0.78rem;letter-spacing:0.02em">' + label + '</span>' +
      '<span style="color:var(--muted);font-size:0.74rem">' + filtered.length + ' technique(s)</span>' +
    '</div>';
  if (collapsed) return header;
  if (!filtered.length) {
    return header + '<div style="padding:0.75rem;color:var(--muted);font-size:0.78rem">No ' + label + ' techniques match</div>';
  }
  var rows = filtered.map(function(t) {
    var key = source + ':' + t.id;
    var expanded = _vexPreviewExpandedKey === key;
    return '<div style="border-bottom:1px solid var(--border)">' +
      '<div style="display:flex;align-items:center;gap:0.5rem;padding:0.5rem 0.6rem 0.5rem 1.7rem;cursor:pointer" onclick="_toggleVexPreviewRow(\'' + source + '\',\'' + x(t.id) + '\')">' +
        '<span style="width:12px;flex-shrink:0;color:var(--muted);font-size:0.7rem">' + (expanded ? '&#9662;' : '&#9656;') + '</span>' +
        '<span style="font-family:var(--font-mono);font-size:0.8rem;flex-shrink:0">' + x(t.id) + '</span>' +
        (t.name ? '<span style="color:var(--muted);font-size:0.78rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + x(t.name) + '</span>' : '') +
      '</div>' +
      (expanded ? _renderVexVariantDetail(source, t.id) : '') +
    '</div>';
  }).join('');
  return header + rows;
}

export function _toggleVexPreviewSection(source) {
  if (source === 'art') _vexPreviewArtCollapsed = !_vexPreviewArtCollapsed;
  else _vexPreviewCalderaCollapsed = !_vexPreviewCalderaCollapsed;
  _renderVexPreviewList();
}

// _toggleVexPreviewRow expands/collapses one technique's variant detail.
// Generation is lazy (only POSTed for the technique actually being
// expanded, never all ~500-800 up front) and cached per "source:techniqueId"
// for as long as the preview stays open, so collapsing and re-expanding
// never re-generates -- and an ART/Caldera technique-ID collision can never
// serve the wrong source's cached variants.
export function _toggleVexPreviewRow(source, techId) {
  var key = source + ':' + techId;
  if (_vexPreviewExpandedKey === key) {
    _vexPreviewExpandedKey = null;
    _renderVexPreviewList();
    return;
  }
  _vexPreviewExpandedKey = key;
  if (!_vexPreviewCache[key]) {
    _vexPreviewCache[key] = { loading: true };
    apicall('/api/variants/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ techniqueId: techId, baseType: source })
    }).then(function(res) {
      _vexPreviewCache[key] = (res && res.error) ? { error: res.error } : { variants: (res && res.templates) || [] };
      // The user may have collapsed this row (or expanded a different one)
      // while the request was in flight -- only re-render if it's still
      // the active one, so a slow response can't pop open a stale row.
      if (_vexPreviewExpandedKey === key) _renderVexPreviewList();
    }).catch(function(e) {
      _vexPreviewCache[key] = { error: e.message || 'Failed to generate variants' };
      if (_vexPreviewExpandedKey === key) _renderVexPreviewList();
    });
  }
  _renderVexPreviewList();
}

function _renderVexVariantDetail(source, techId) {
  var entry = _vexPreviewCache[source + ':' + techId];
  if (!entry || entry.loading) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--muted);font-size:0.76rem">Generating variants…</div>';
  }
  if (entry.error) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--danger);font-size:0.76rem">' + x(entry.error) + '</div>';
  }
  var variants = entry.variants || [];
  if (!variants.length) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--muted);font-size:0.76rem">No variants generated for this technique</div>';
  }
  return '<div style="padding:0.4rem 0.6rem 0.6rem 1.9rem;display:flex;flex-direction:column;gap:0.4rem">' +
    variants.map(function(v) {
      var riskColor = v.riskLevel === 'ADVANCED' ? 'var(--danger)' : v.riskLevel === 'MODERATE' ? 'var(--warning)' : 'var(--success)';
      return '<div style="background:var(--elevated);border:1px solid var(--border);border-radius:6px;padding:0.4rem 0.55rem;font-size:0.72rem">' +
        '<div style="display:flex;gap:0.6rem;flex-wrap:wrap;color:var(--muted)">' +
          '<span>Encoding: <b class="u-text">' + x(v.encoding || '—') + '</b></span>' +
          '<span>Context: <b class="u-text">' + x(v.execContext || '—') + '</b></span>' +
          '<span>Evasion: <b class="u-text">' + x(v.evasion || 'none') + '</b></span>' +
          '<span>Risk: <b style="color:' + riskColor + '">' + x(v.riskLevel || '—') + '</b></span>' +
        '</div>' +
      '</div>';
    }).join('') +
  '</div>';
}

function _renderEMPreviewList() {
  var listEl = document.getElementById('sweep-preview-list');
  var countEl = document.getElementById('sweep-preview-count');
  if (!listEl) return;

  var fixedIds = {};
  EM_CATALOG.forEach(function(e) { fixedIds[e.id] = true; });
  // Extra scenarios are additional Endpoint Mastery-category scenarios
  // (id starting "em-", or tagged endpoint-mastery -- see scenarioCategoryOf)
  // beyond the 14 fixed layers, e.g. a custom or threat-intel-generated EM
  // scenario. Standard/non-EM scenarios from the main Scenarios library are
  // NOT valid candidates here, even though they're also in `scenarios`.
  var extraCandidates = (state.scenarios || []).filter(function(s) {
    return s.id && !fixedIds[s.id] && scenarioCategoryOf(s) === 'em';
  });
  var q = (_emExtraSearch || '').trim().toLowerCase();
  var extraFiltered = q ? extraCandidates.filter(function(s) {
    return (s.name || '').toLowerCase().indexOf(q) !== -1 || s.id.toLowerCase().indexOf(q) !== -1;
  }) : extraCandidates;
  var extraSelectedCount = Object.keys(_emExtraSelected).length;

  if (countEl) countEl.textContent = EM_CATALOG.length + ' fixed layer(s), ' + extraSelectedCount + ' extra selected';

  var fixedHtml = EM_CATALOG.map(function(layer) {
    var expanded = _emPreviewExpandedId === layer.id;
    return '<div style="border-bottom:1px solid var(--border)">' +
      '<div style="display:flex;align-items:center;gap:0.5rem;padding:0.5rem 0.6rem;cursor:pointer" onclick="_toggleEMPreviewRow(\'' + x(layer.id) + '\')">' +
        '<span style="width:12px;flex-shrink:0;color:var(--muted);font-size:0.7rem">' + (expanded ? '&#9662;' : '&#9656;') + '</span>' +
        '<span style="font-weight:600;font-size:0.8rem;flex-shrink:0">Layer ' + x(layer.num) + ' — ' + x(layer.name) + '</span>' +
        '<span style="color:var(--muted);font-size:0.76rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + x(layer.desc) + '</span>' +
      '</div>' +
      (expanded ? _renderEMLayerDetail(layer.id) : '') +
    '</div>';
  }).join('');

  var extraHeaderHtml = '<div style="padding:0.5rem 0.6rem;font-size:0.7rem;font-weight:600;letter-spacing:0.03em;color:var(--muted);background:var(--elevated)">' +
    'EXTRA SCENARIOS &mdash; optional, appended after the ' + EM_CATALOG.length + ' fixed layers</div>';
  var extraRowsHtml = extraFiltered.length ? extraFiltered.map(function(s) {
    var checked = !!_emExtraSelected[s.id];
    return '<label style="display:flex;align-items:center;gap:0.55rem;padding:0.45rem 0.6rem;cursor:pointer;border-bottom:1px solid var(--border)">' +
      '<input type="checkbox"' + (checked ? ' checked' : '') + ' onchange="_toggleEMExtraScenario(\'' + x(s.id) + '\')">' +
      '<span style="font-size:0.8rem;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + x(s.name || s.id) + '</span>' +
      '<span style="font-family:var(--font-mono);font-size:0.68rem;color:var(--muted);flex-shrink:0">' + x(s.id) + '</span>' +
    '</label>';
  }).join('') : '<div style="padding:0.6rem;color:var(--muted);font-size:0.76rem">No scenarios match</div>';

  listEl.innerHTML = fixedHtml + extraHeaderHtml + extraRowsHtml;
}

export function _setEMExtraSearch(v) { _emExtraSearch = v; _renderEMPreviewList(); }

// _toggleEMExtraScenario only flips selection state -- it does not
// re-render the search input (renderSweepPreview builds filters once per
// open, see its own comment), so typing then checking boxes never loses
// focus.
export function _toggleEMExtraScenario(id) {
  if (_emExtraSelected[id]) delete _emExtraSelected[id];
  else _emExtraSelected[id] = true;
  _renderEMPreviewList();
  var summaryEl = document.getElementById('sweep-preview-summary');
  var emTargets = _sweepPreviewTargets;
  var extraCount = Object.keys(_emExtraSelected).length;
  if (summaryEl && emTargets) {
    summaryEl.textContent = 'Targeting ' + (emTargets.agentIds || []).length + ' agent(s). ' +
      EM_CATALOG.length + ' fixed layers' + (extraCount ? ' + ' + extraCount + ' extra scenario(s)' : '') +
      ' run sequentially per agent.';
  }
}

// _toggleEMPreviewRow mirrors _toggleVexPreviewRow exactly, one store
// swapped for the other: lazy per-layer fetch, cached while the preview
// stays open.
export function _toggleEMPreviewRow(layerId) {
  if (_emPreviewExpandedId === layerId) {
    _emPreviewExpandedId = null;
    _renderEMPreviewList();
    return;
  }
  _emPreviewExpandedId = layerId;
  if (!_emPreviewCache[layerId]) {
    _emPreviewCache[layerId] = { loading: true };
    apicall('/api/scenarios/' + encodeURIComponent(layerId)).then(function(s) {
      _emPreviewCache[layerId] = { scenario: s || {} };
      if (_emPreviewExpandedId === layerId) _renderEMPreviewList();
    }).catch(function(e) {
      _emPreviewCache[layerId] = { error: e.message || 'Failed to load layer' };
      if (_emPreviewExpandedId === layerId) _renderEMPreviewList();
    });
  }
  _renderEMPreviewList();
}

function _renderEMLayerDetail(layerId) {
  var entry = _emPreviewCache[layerId];
  if (!entry || entry.loading) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--muted);font-size:0.76rem">Loading…</div>';
  }
  if (entry.error) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--danger);font-size:0.76rem">' + x(entry.error) + '</div>';
  }
  var s = entry.scenario || {};
  var steps = s.steps || [];
  // Some EM layers may be authored as pure ART-technique lists (no literal
  // step/command data of their own) rather than custom steps -- fall back
  // to the technique IDs alone rather than showing nothing.
  if (!steps.length && (s.artTechniques || []).length) {
    return '<div style="padding:0.4rem 0.6rem 0.6rem 1.9rem;display:flex;flex-direction:column;gap:0.3rem">' +
      s.artTechniques.map(function(tid) {
        return '<div style="font-family:var(--font-mono);font-size:0.76rem;color:var(--text)">' + x(tid) + '</div>';
      }).join('') +
    '</div>';
  }
  if (!steps.length) {
    return '<div style="padding:0.6rem 0.6rem 0.6rem 1.9rem;color:var(--muted);font-size:0.76rem">No steps found for this layer</div>';
  }
  // Deliberately shows what a step DOES and WHY (blast radius, risk,
  // reversibility, expected telemetry/detection) rather than its raw
  // PowerShell/command text -- this is an operator-facing preview of what a
  // sweep is about to run, not a code viewer. Every step already carries
  // this metadata for exactly this purpose (see Step.BlastRadius etc.,
  // internal/scenario/types.go).
  return '<div style="padding:0.4rem 0.6rem 0.6rem 1.9rem;display:flex;flex-direction:column;gap:0.4rem">' +
    steps.map(function(st) {
      var riskCol = st.risk === 'high' ? 'var(--danger)' : st.risk === 'medium' ? 'var(--warning)' : 'var(--success)';
      var badges =
        (st.risk ? '<span class="sbadge" style="background:rgba(0,0,0,0.15);color:' + riskCol + '">' + x(st.risk) + ' risk</span>' : '') +
        (st.reversible ? '<span class="sbadge" style="background:rgba(35,134,54,0.15);color:var(--success)">reversible</span>' : '');
      var telemetry = (st.telemetry || []).length ? '<div style="color:var(--muted);line-height:1.4;margin-top:0.2rem"><strong class="u-text">Telemetry:</strong> ' + st.telemetry.map(x).join(' · ') + '</div>' : '';
      var detection = (st.detection || []).length ? '<div style="color:var(--muted);line-height:1.4;margin-top:0.2rem"><strong class="u-text">Detection:</strong> ' + st.detection.map(x).join(' · ') + '</div>' : '';
      var blast = st.blastRadius ? '<div style="color:var(--muted);line-height:1.4;margin-top:0.2rem"><strong class="u-text">What it does:</strong> ' + x(st.blastRadius) + '</div>' : '';
      var noDetail = (!blast && !telemetry && !detection) ? '<div style="color:var(--muted);margin-top:0.2rem">No additional details available for this step.</div>' : '';
      return '<div style="background:var(--elevated);border:1px solid var(--border);border-radius:6px;padding:0.45rem 0.6rem;font-size:0.72rem">' +
        '<div style="display:flex;align-items:center;gap:0.4rem;flex-wrap:wrap">' +
          (st.techniqueId ? '<span style="font-family:var(--font-mono);color:var(--text);font-weight:600">' + x(st.techniqueId) + '</span>' : '') +
          '<span class="u-text">' + x(st.name || '') + '</span>' +
          badges +
        '</div>' +
        blast + telemetry + detection + noDetail +
      '</div>';
    }).join('') +
  '</div>';
}

var _emSweepPollTimer = null;

var _emSweepPollFailing = false; // true while pollEMSweepProgress' fetch is failing -- see pollVexSweeps' identical rationale

export function openEMSweepProgress(sweepId) {
  state._emSweepCurrentId = sweepId;
  document.getElementById('em-sweep-progress-actions').innerHTML = '';
  document.getElementById('em-sweep-progress-overlay').classList.add('open');
  pollEMSweepProgress();
  if (_emSweepPollTimer) clearInterval(_emSweepPollTimer);
  _emSweepPollTimer = setInterval(pollEMSweepProgress, 3000);
}

export function closeEMSweepProgress() {
  document.getElementById('em-sweep-progress-overlay').classList.remove('open');
  if (_emSweepPollTimer) { clearInterval(_emSweepPollTimer); _emSweepPollTimer = null; }
  state._emSweepCurrentId = null;
}

// cancelEMSweep mirrors stopVexSweep's exact pattern -- the server-side
// POST /api/em/sweeps/{id}/cancel endpoint already existed and already
// correctly handles both 'running' and 'agent_disconnected' sweeps; this
// was simply never wired to anything clickable.
export function cancelEMSweep(sweepId) {
  if (!confirm('Stop this sweep? The current layer finishes or is cancelled; no further layers dispatch.')) return;
  apicall('/api/em/sweeps/' + encodeURIComponent(sweepId) + '/cancel', { method: 'POST' })
    .then(function() { pollEMSweepProgress(); })
    .catch(function(e) { showToast(e.message || 'Failed to stop sweep', 'err'); });
}

function pollEMSweepProgress() {
  if (!state._emSweepCurrentId) return;
  // Fetches both the sweep's own status (layers, currentIndex, overall
  // status) AND the real per-layer run data (results, progress) every
  // tick -- without the second fetch this drawer could only ever show a
  // done/running/pending icon per layer, with no way to see what a
  // completed (or halted-mid-sweep) layer actually found. Mirrors
  // openSweepDrilldown's childRuns rendering for Full Variant Sweep.
  Promise.all([
    apicall('/api/em/sweeps/' + encodeURIComponent(state._emSweepCurrentId)),
    apicall('/api/em/sweeps/' + encodeURIComponent(state._emSweepCurrentId) + '/runs')
  ]).then(function(res) {
    _emSweepPollFailing = false;
    var sw = res[0];
    if (!sw || sw.error) return;
    var runs = (res[1] && res[1].runs) || [];
    renderEMSweepProgress(sw, runs);
    if (sw.status !== 'running' && sw.status !== 'agent_disconnected' && _emSweepPollTimer) {
      clearInterval(_emSweepPollTimer);
      _emSweepPollTimer = null;
    }
  }).catch(function() {
    // See pollVexSweeps' identical rationale: this 3s poll runs for as long
    // as the progress drawer is open (the operator can leave it open
    // indefinitely) and previously failed silently forever. One toast per
    // failure episode, self-clearing on the next successful poll.
    if (!_emSweepPollFailing) {
      _emSweepPollFailing = true;
      showToast('Sweep progress refresh failing — will keep retrying', 'err');
    }
  });
}

function renderEMSweepProgress(sw, runs) {
  document.getElementById('em-sweep-progress-title').textContent = 'EM Full Sweep — ' + x(sw.agentId);
  document.getElementById('em-sweep-progress-summary').innerHTML =
    '<strong>' + sw.completedLayers + '/' + sw.totalLayers + '</strong> layers complete &middot; status: ' + x(sweepStatusLabel(sw.status)) +
    (sw.error ? '<div style="color:var(--danger);margin-top:0.3rem">' + x(sw.error) + '</div>' : '');
  // Combined report only once the sweep has stopped advancing -- a partial
  // union of whatever layers happened to finish so far is a lot less useful
  // for EM's 14 fixed-layer structure than waiting for the real thing.
  var terminal = sw.status !== 'running' && sw.status !== 'agent_disconnected';
  document.getElementById('em-sweep-progress-actions').innerHTML = terminal
    ? '<button class="btn btn-outline btn-sm" onclick="window.open(\'/api/em/sweeps/' + encodeURIComponent(sw.id) + '/report\',\'_blank\')" title="Open the combined EM sweep report">&#8599; HTML Report</button> ' +
      '<button class="btn btn-outline btn-sm" onclick="downloadEMSweepReport(\'' + x(sw.id) + '\')" title="Download the combined EM sweep report as a PDF file">&#8595; PDF Report</button>'
    // Previously there was no cancel control here at all -- a sweep stuck in
    // agent_disconnected (e.g. the agent's heartbeat looks fine but its
    // WebSocket never reconnected) had a working server-side cancel endpoint
    // (POST /api/em/sweeps/{id}/cancel) with no UI path to reach it, so an
    // operator had no way to unblock a new sweep short of a raw API call.
    : '<button class="btn btn-outline-red btn-sm" onclick="cancelEMSweep(\'' + x(sw.id) + '\')" title="Stop this sweep -- the current layer finishes or is cancelled; no further layers dispatch">&#9632; Cancel Sweep</button>' +
      (sw.status === 'agent_disconnected' ? ' <span class="tiny u-warning">Paused -- agent not connected. Will resume automatically on reconnect, or cancel to start a new sweep now.</span>' : '');
  var runsByScenario = {};
  (runs || []).forEach(function(r) { runsByScenario[r.scenarioId] = r; });
  var list = document.getElementById('em-sweep-progress-list');
  list.innerHTML = (sw.layers || []).map(function(layerId, i) {
    var state = i < sw.currentIndex ? 'done' : (i === sw.currentIndex && sw.status === 'running') ? 'running' : 'pending';
    var color = state === 'done' ? 'var(--success)' : state === 'running' ? 'var(--accent)' : 'var(--muted)';
    var label = state === 'done' ? '&#10003;' : state === 'running' ? '&#9679;' : '&#9675;';
    var r = runsByScenario[layerId];
    var actionHtml = '';
    if (r) {
      var badge = verdictBadge(r, r.status);
      if (r.id && r.status === 'running') {
        actionHtml = '<button class="btn btn-outline btn-sm" onclick="openRunPanel(\'' + x(r.id) + '\',\'' + x(r.name).replace(/'/g,'&#39;') + '\',' + ((r.progress && r.progress.stepsTotal) || 0) + ',\'' + x(r.mode||'') + '\',\'' + x(r.maxPrivilege||'') + '\')">&#9673; Live</button>';
      } else if (verdictCounts(r).total) {
        actionHtml = '<button class="btn btn-outline btn-sm" onclick=\'viewRunResults(' + JSON.stringify(r).replace(/'/g,"&#39;") + ')\'>' + badge + '</button>';
      } else if (r.id && r.progress) {
        // A cancelled/partial layer (e.g. the agent disconnected mid-sweep)
        // never gets the agent's one atomic `results` write, so verdictCounts(r).total is 0 --
        // but its per-step pass/fail counts already streamed in live
        // (r.progress) and are still queryable via openRunPanel, so this
        // reuses that real data instead of leaving a completed-but-halted
        // layer with no way to see what it found.
        var pr = r.progress;
        var toBadge = pr.stepsFailed + ' fail / ' + pr.stepsPassed + ' pass' + (pr.stepsTimeout ? ' / ' + pr.stepsTimeout + ' timeout' : '');
        actionHtml = '<button class="btn btn-outline btn-sm" onclick="openRunPanel(\'' + x(r.id) + '\',\'' + x(r.name).replace(/'/g,'&#39;') + '\',' + (pr.stepsTotal || 0) + ',\'' + x(r.mode||'') + '\',\'' + x(r.maxPrivilege||'') + '\')">' + toBadge + '</button>';
      } else {
        actionHtml = '<span class="tiny muted">' + x(badge) + '</span>';
      }
    }
    return '<li style="display:flex;align-items:center;justify-content:space-between;gap:0.5rem;padding:0.3rem 0">' +
      '<span style="display:flex;align-items:center;gap:0.5rem;color:' + color + '"><span>' + label + '</span><span>' + x(layerId) + '</span></span>' +
      '<span style="white-space:nowrap">' + actionHtml + '</span></li>';
  }).join('');
  var stopBtn = document.getElementById('em-sweep-stop-btn');
  stopBtn.style.display = (sw.status === 'running' || sw.status === 'agent_disconnected') ? '' : 'none';
}

export function stopEMSweep(sweepId) {
  sweepId = sweepId || state._emSweepCurrentId;
  if (!sweepId) return;
  if (!confirm('Stop this EM sweep? The current layer keeps running to completion but no further layers will be dispatched.')) return;
  apicall('/api/em/sweeps/' + encodeURIComponent(sweepId) + '/cancel', { method: 'POST' }).then(function() {
    if (sweepId === state._emSweepCurrentId) pollEMSweepProgress();
    loadRuns();
  }).catch(function(e) { showToast(e.message, 'err'); });
}