// GENERATED by web/tools/split.mjs from tools/monolith.html -- do not edit during G1c.
import { apicall } from '../core/api.js';
import { x } from '../core/escape.js';


// ── Variant Coverage Report rendering ────────────────────────────────────────

export function renderVariantCoverage(data) {
  var nc = ''.replace; // no-op; used for clarity
  if (!data || data.variantDepth === 'none' || !data.techniques || !data.techniques.length) {
    return '<div style="color:var(--muted);font-size:0.78rem;padding:2rem 0;text-align:center">' +
      '<div style="font-size:1.5rem;margin-bottom:0.5rem">&#9633;</div>' +
      '<div>No variant data for this run.</div>' +
      '<div style="margin-top:0.4rem;font-size:0.7rem">Re-run with Variant depth: Quick, Standard, or Full.</div>' +
    '</div>';
  }

  var s = data.summary || {};
  var techs = data.techniques || [];
  // vetoed: B5's agent-side destructive-action guardrail refused the step --
  // a policy decision, not a security-control outcome, so it gets its own
  // warning-amber treatment distinct from error/skipped's muted grey (final
  // whole-branch review I3; variantVerdictStr, internal/api/handlers.go,
  // emits exactly this string for a vetoed variant result).
  var VCOL  = { blocked:'var(--success)', detected:'var(--warning)', logged:'#d29922', bypassed:'var(--danger)', error:'var(--muted)', skipped:'var(--muted)', vetoed:'var(--warning)' };
  var VBG   = { blocked:'rgba(35,134,54,0.12)', detected:'rgba(210,153,34,0.12)', logged:'rgba(210,153,34,0.08)', bypassed:'rgba(218,54,51,0.12)', error:'rgba(154,169,188,0.06)', skipped:'rgba(154,169,188,0.04)', vetoed:'rgba(210,153,34,0.12)' };
  var VICON = { blocked:'&#10003;', detected:'&#9888;', logged:'&#9685;', bypassed:'&#10007;', error:'?', skipped:'&#9675;', vetoed:'&#128683;' };

  function tile(label, val, sub, col) {
    return '<div style="background:var(--elevated);border:1px solid var(--border);border-top:2px solid ' + col + ';border-radius:4px;padding:0.55rem 0.75rem;flex:1;min-width:100px">' +
      '<div style="font-size:0.58rem;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);margin-bottom:0.2rem">' + label + '</div>' +
      '<div style="font-size:1.35rem;font-weight:700;color:' + col + ';line-height:1.1">' + val + '</div>' +
      (sub ? '<div style="font-size:0.65rem;color:var(--muted);margin-top:0.1rem">' + sub + '</div>' : '') +
    '</div>';
  }
  function verdictBadge(v) {
    var col = VCOL[v] || 'var(--muted)';
    return '<span style="display:inline-flex;align-items:center;gap:3px;background:' + (VBG[v]||'rgba(154,169,188,0.06)') + ';border:1px solid ' + col + ';border-radius:3px;padding:1px 6px;font-size:0.65rem;color:' + col + '">' + (VICON[v]||'?') + ' ' + x(v) + '</span>';
  }
  function dimBadges(arr) {
    return (arr||[]).map(function(d){ return '<span style="display:inline-block;background:var(--surface);border:1px solid var(--border);border-radius:3px;padding:1px 5px;font-size:0.62rem;color:var(--muted);margin:1px">' + x(d) + '</span>'; }).join('');
  }

  var bypassPct = (s.bypassRate || 0).toFixed(1);
  var coverPct  = (s.coverageScore || 0).toFixed(1);
  var bypassCol = s.bypassRate > 20 ? 'var(--danger)' : s.bypassRate > 5 ? 'var(--warning)' : 'var(--success)';
  var coverCol  = s.coverageScore >= 90 ? 'var(--success)' : s.coverageScore >= 70 ? 'var(--warning)' : 'var(--danger)';

  // ── Section 1: Summary tiles ─────────────────────────────────────────────
  var summaryHtml =
    '<div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-bottom:1rem">' +
      tile('Techniques Tested',   s.techniquesTotal || 0, 'via variant engine', 'var(--accent)') +
      tile('Variants Executed',   s.variantsExecuted || 0, (s.variantDepth||data.variantDepth||'') + ' depth', 'var(--accent)') +
      tile('Blocked',             s.blocked || 0, (s.blocked + s.detected > 0 ? coverPct + '% prevention' : 'no data'), coverCol) +
      tile('Bypass Rate',         bypassPct + '%', (s.techniquesWithBypass||0) + ' technique' + (s.techniquesWithBypass===1?'':'s') + ' exposed', bypassCol) +
    '</div>';

  // ── Section 2: Bypass Findings (only when bypasses exist) ────────────────
  var bypassedTechs = techs.filter(function(t){ return t.hasBypass; });
  var bypassHtml = '';
  if (bypassedTechs.length) {
    var findings = bypassedTechs.map(function(t, i) {
      var bb = t.bestBypass;
      var bypassLabel = bb ? [bb.encoding, bb.executionContext, bb.privilege].filter(Boolean).map(function(d){
        return d.charAt(0).toUpperCase() + d.slice(1);
      }).join(' + ') : 'Unknown';
      var proxyHtml = (bb && bb.proxyTechniqueId) ?
        '<div style="margin-top:0.3rem"><span style="color:var(--muted);font-size:0.66rem">Proxy Technique</span> <span style="color:var(--accent);font-size:0.72rem;font-weight:600">' + x(bb.proxyTechniqueId) + '</span></div>' : '';
      var detectionNote = (bb && (bb.verdict === 'detected' || bb.verdict === 'logged')) ? 'Detected' : 'Not Observed';
      var detCol = (detectionNote === 'Detected') ? 'var(--warning)' : 'var(--muted)';

      var points = (t.remediationPoints || []).slice(0, 4).map(function(p){
        return '<li style="margin-bottom:0.3rem">' + x(p) + '</li>';
      }).join('');

      return '<div style="background:var(--elevated);border:1px solid var(--border);border-left:3px solid var(--danger);border-radius:0 4px 4px 0;padding:0.75rem 1rem;margin-bottom:0.75rem">' +
        '<div style="display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;flex-wrap:wrap">' +
          '<div style="flex:1;min-width:200px">' +
            '<div style="display:flex;align-items:center;gap:0.5rem;margin-bottom:0.35rem">' +
              '<span style="font-size:0.72rem;font-weight:700;color:var(--accent);letter-spacing:.04em">' + x(t.techniqueId) + '</span>' +
              '<span style="color:var(--muted);font-size:0.68rem">' + x(t.techniqueName) + '</span>' +
              verdictBadge('bypassed') +
            '</div>' +
            '<div style="font-size:0.7rem;color:var(--fg);margin-bottom:0.25rem"><span class="u-muted">Best Bypass: </span><strong>' + x(bypassLabel) + '</strong></div>' +
            proxyHtml +
            '<div style="margin-top:0.2rem"><span style="color:var(--muted);font-size:0.66rem">Detection: </span><span style="color:' + detCol + ';font-size:0.68rem;font-weight:600">' + detectionNote + '</span></div>' +
          '</div>' +
          '<div style="flex:0 0 auto;text-align:right">' +
            '<div style="font-size:0.6rem;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)">Bypass Rate</div>' +
            '<div style="font-size:1.4rem;font-weight:700;color:var(--danger)">' + (t.bypassRate||0).toFixed(0) + '%</div>' +
            '<div style="font-size:0.62rem;color:var(--muted)">' + (t.bypassed||0) + '/' + (t.variantsExecuted||0) + ' variants</div>' +
          '</div>' +
        '</div>' +
        '<div style="margin-top:0.65rem;padding-top:0.55rem;border-top:1px solid var(--border)">' +
          '<div style="font-size:0.66rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:var(--warning);margin-bottom:0.35rem">Recommendation</div>' +
          '<div style="font-size:0.72rem;color:var(--fg);margin-bottom:0.4rem">' + x(t.headline) + '</div>' +
          (points ? '<ul style="margin:0;padding-left:1.2em;font-size:0.7rem;color:var(--muted)">' + points + '</ul>' : '') +
        '</div>' +
        '<div style="margin-top:0.5rem;display:flex;gap:0.35rem;flex-wrap:wrap;align-items:center">' +
          '<button class="btn btn-sm btn-outline" style="font-size:0.62rem;padding:2px 8px" onclick="loadVariantMatrix(this,\'' + x(data.runId) + '\',\'' + x(t.techniqueId) + '\')">' +
            '&#9783; View variant matrix' +
          '</button>' +
        '</div>' +
      '</div>';
    }).join('');

    bypassHtml =
      '<div class="u-mb-1">' +
        '<div style="font-size:0.65rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:var(--danger);margin-bottom:0.55rem;padding-bottom:0.3rem;border-bottom:1px solid var(--border)">' +
          '&#9888; Bypass Findings (' + bypassedTechs.length + ')' +
        '</div>' +
        findings +
      '</div>';
  }

  // ── Section 3: Technique Coverage table ──────────────────────────────────
  var rows = techs.map(function(t) {
    var allowedTotal = (t.bypassed||0) + (t.detected||0) + (t.logged||0);
    var brCol = t.bypassRate > 20 ? 'var(--danger)' : t.bypassRate > 5 ? 'var(--warning)' : 'var(--success)';
    var bbShort = '';
    if (t.bestBypass) {
      var bb = t.bestBypass;
      bbShort = [bb.encoding, bb.executionContext, bb.privilege].filter(Boolean).map(function(d){
        return '<span style="font-size:0.6rem;background:var(--surface);border:1px solid var(--border);border-radius:3px;padding:0px 4px;margin:1px">' + x(d) + '</span>';
      }).join('');
    }
    return '<tr>' +
      '<td style="font-weight:600;color:var(--accent)">' + x(t.techniqueId) + '<br><span style="font-weight:400;color:var(--muted);font-size:0.65rem">' + x(t.techniqueName) + '</span></td>' +
      '<td style="text-align:right">' + (t.variantsExecuted||0) + '</td>' +
      '<td style="text-align:right;color:var(--success)">' + (t.blocked||0) + '</td>' +
      '<td style="text-align:right;color:var(--warning)">' + (t.detected||0) + '</td>' +
      '<td style="text-align:right;color:var(--danger)">' + ((t.bypassed||0)+(t.logged||0)) + '</td>' +
      '<td style="text-align:right;color:' + brCol + ';font-weight:700">' + (t.bypassRate||0).toFixed(1) + '%</td>' +
      '<td>' + bbShort + '</td>' +
    '</tr>';
  }).join('');

  var tableHtml =
    '<div class="u-mb-1">' +
      '<div style="font-size:0.65rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:var(--accent);margin-bottom:0.55rem;padding-bottom:0.3rem;border-bottom:1px solid var(--border)">Technique Coverage</div>' +
      '<div style="overflow-x:auto">' +
        '<table style="width:100%;border-collapse:collapse;font-size:0.72rem">' +
          '<thead><tr style="color:var(--muted);font-size:0.6rem;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid var(--border)">' +
            '<th style="text-align:left;padding:4px 6px">Technique</th>' +
            '<th style="text-align:right;padding:4px 6px">Tested</th>' +
            '<th style="text-align:right;padding:4px 6px">Blocked</th>' +
            '<th style="text-align:right;padding:4px 6px">Detected</th>' +
            '<th style="text-align:right;padding:4px 6px">Allowed</th>' +
            '<th style="text-align:right;padding:4px 6px">Bypass%</th>' +
            '<th style="text-align:left;padding:4px 6px">Best Bypass</th>' +
          '</tr></thead>' +
          '<tbody>' + rows + '</tbody>' +
        '</table>' +
      '</div>' +
    '</div>';

  return '<div style="padding:0.25rem 0">' + summaryHtml + bypassHtml + tableHtml + '</div>';
}

// Loads and renders the per-technique variant matrix into an inline container.
// Called by the "View variant matrix" button inside a bypass finding card.
export function loadVariantMatrix(btn, runId, techniqueId) {
  var card = btn.closest ? btn.closest('[data-matrix]') : null;
  var containerId = 'vmatrix-' + techniqueId.replace(/\./g, '-');
  var existing = document.getElementById(containerId);
  if (existing) { existing.remove(); btn.textContent = '&#9783; View variant matrix'; return; }

  btn.textContent = 'Loading…';
  apicall('/api/scenarios/runs/' + encodeURIComponent(runId) + '/variant-coverage/' + encodeURIComponent(techniqueId))
    .then(function(data) {
      btn.textContent = '&#9783; Hide variant matrix';
      var rows = (data.rows || []);
      var VCOL = { blocked:'var(--success)', detected:'var(--warning)', logged:'#d29922', bypassed:'var(--danger)', error:'var(--muted)', skipped:'var(--muted)', vetoed:'var(--warning)' };
      var trs = rows.map(function(r) {
        var col = VCOL[r.verdict] || 'var(--muted)';
        var bestMark = r.isBestBypass ? ' &#9733;' : '';
        return '<tr style="background:' + (r.isBestBypass ? 'rgba(218,54,51,0.08)' : '') + ';border-bottom:1px solid var(--border)">' +
          '<td style="padding:3px 6px;color:var(--accent);font-size:0.65rem">' + x(r.encoding) + '</td>' +
          '<td style="padding:3px 6px;font-size:0.65rem">' + x(r.privilege) + '</td>' +
          '<td style="padding:3px 6px;font-size:0.65rem">' + x(r.executionContext) + '</td>' +
          '<td style="padding:3px 6px;font-size:0.65rem;color:var(--muted)">' + x(r.proxyTechniqueId||'—') + '</td>' +
          '<td style="padding:3px 6px"><span style="font-size:0.62rem;font-weight:600;color:' + col + '">' + x(r.verdict) + bestMark + '</span></td>' +
          '<td style="padding:3px 6px;font-size:0.62rem;color:var(--muted)">' + (r.durationMs ? r.durationMs + 'ms' : '—') + '</td>' +
        '</tr>';
      }).join('');

      var html =
        '<div id="' + containerId + '" style="margin-top:0.75rem;border:1px solid var(--border);border-radius:4px;overflow:hidden">' +
          '<div style="background:var(--surface);padding:0.35rem 0.75rem;font-size:0.62rem;font-weight:700;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)">Variant Matrix — ' + x(techniqueId) + ' (' + rows.length + ' variants)</div>' +
          '<div style="overflow-x:auto">' +
            '<table style="width:100%;border-collapse:collapse;font-size:0.7rem">' +
              '<thead><tr style="color:var(--muted);font-size:0.58rem;text-transform:uppercase;border-bottom:1px solid var(--border)">' +
                '<th style="padding:3px 6px;text-align:left">Encoding</th>' +
                '<th style="padding:3px 6px;text-align:left">Privilege</th>' +
                '<th style="padding:3px 6px;text-align:left">Context</th>' +
                '<th style="padding:3px 6px;text-align:left">Proxy Tech</th>' +
                '<th style="padding:3px 6px;text-align:left">Verdict</th>' +
                '<th style="padding:3px 6px;text-align:left">Duration</th>' +
              '</tr></thead>' +
              '<tbody>' + trs + '</tbody>' +
            '</table>' +
          '</div>' +
        '</div>';
      btn.insertAdjacentHTML('afterend', html);
    })
    .catch(function() {
      btn.textContent = '&#9783; View variant matrix';
    });
}

// Renders the visual attack flow from the /attackflow API response.
// nodes: AttackFlowNode[] ordered by kill-chain tactic phase.
// summary: {total, blocked, detected, logged, bypassed, errors, skipped}
export function renderAttackFlow(nodes, summary) {
  if (!nodes || !nodes.length) {
    return '<div style="color:var(--muted);text-align:center;padding:2rem 0;font-size:0.78rem">No attack flow data for this run.</div>';
  }

  var VERDICT_COLOR = { blocked:'var(--success)', detected:'var(--warning)', logged:'#d29922', bypassed:'var(--danger)', error:'var(--muted)', skipped:'var(--muted)', vetoed:'var(--warning)' };
  var VERDICT_BG    = { blocked:'rgba(35,134,54,0.08)', detected:'rgba(210,153,34,0.08)', logged:'rgba(210,153,34,0.05)', bypassed:'rgba(218,54,51,0.08)', error:'rgba(154,169,188,0.05)', skipped:'rgba(154,169,188,0.04)', vetoed:'rgba(210,153,34,0.08)' };
  var VERDICT_ICON  = { blocked:'&#10003;', detected:'&#9888;', logged:'&#9685;', bypassed:'&#10007;', error:'?', skipped:'&#9675;', vetoed:'&#128683;' };

  function summTile(n, label, color) {
    return '<div style="flex:1;min-width:68px;background:var(--elevated);border:1px solid var(--border);border-top:2px solid ' + color + ';border-radius:4px;padding:0.35rem 0.55rem">' +
      '<div style="font-size:1.05rem;font-weight:700;color:' + color + ';line-height:1.2">' + n + '</div>' +
      '<div style="font-size:0.6rem;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)">' + label + '</div>' +
    '</div>';
  }

  var s = summary || {};
  var summaryHtml =
    '<div style="display:flex;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap">' +
      summTile(s.blocked  || 0, 'Blocked',  'var(--success)') +
      summTile(s.detected || 0, 'Detected', 'var(--warning)') +
      summTile(s.logged   || 0, 'Logged',   '#d29922') +
      summTile(s.bypassed || 0, 'Bypassed', 'var(--danger)') +
      (s.errors > 0 ? summTile(s.errors, 'Error', 'var(--muted)') : '') +
    '</div>';

  // Group nodes by tactic (they arrive pre-sorted by kill-chain phase)
  var phases = [];
  var curTactic = null;
  var curNodes  = [];
  nodes.forEach(function(n) {
    if (n.tactic !== curTactic) {
      if (curNodes.length) phases.push({ tactic: curTactic, label: curNodes[0].tacticLabel || curTactic, nodes: curNodes });
      curTactic = n.tactic;
      curNodes  = [n];
    } else {
      curNodes.push(n);
    }
  });
  if (curNodes.length) phases.push({ tactic: curTactic, label: curNodes[0].tacticLabel || curTactic, nodes: curNodes });

  var flowHtml = '';
  phases.forEach(function(phase, pi) {
    var anyBypassed = phase.nodes.some(function(n) { return n.verdict === 'bypassed'; });
    var allBlocked  = phase.nodes.every(function(n) { return n.isStopPoint; });
    var phaseColor  = allBlocked ? 'var(--success)' : anyBypassed ? 'var(--danger)' : 'var(--warning)';

    flowHtml += '<div style="font-size:0.62rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:' + phaseColor + ';padding:0.28rem 0.6rem;background:var(--elevated);border-left:2px solid ' + phaseColor + ';border-radius:0 3px 3px 0;margin-bottom:0.4rem">' + x(phase.label || phase.tactic || 'Unknown') + '</div>';

    phase.nodes.forEach(function(n) {
      var vc  = VERDICT_COLOR[n.verdict] || 'var(--muted)';
      var vbg = VERDICT_BG[n.verdict]    || 'rgba(154,169,188,0.04)';
      var vi  = VERDICT_ICON[n.verdict]  || '&#183;';

      flowHtml +=
        '<div style="background:' + vbg + ';border:1px solid var(--border);border-left:3px solid ' + vc + ';border-radius:0 4px 4px 0;padding:0.45rem 0.65rem;margin-bottom:0.3rem">' +
          '<div style="display:flex;align-items:center;gap:0.45rem">' +
            '<code style="font-size:0.68rem;color:var(--accent);flex-shrink:0;min-width:5.5rem">' + x(n.techniqueId || '—') + '</code>' +
            '<span style="font-size:0.75rem;color:var(--text);flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="' + x(n.techniqueName || '') + '">' + x(n.techniqueName || '') + '</span>' +
            '<span style="font-size:0.65rem;font-weight:600;color:' + vc + ';border:1px solid ' + vc + '55;border-radius:3px;padding:0.05rem 0.28rem;flex-shrink:0;white-space:nowrap">' + vi + '&nbsp;' + x(n.verdictLabel || n.verdict) + '</span>' +
          '</div>' +
          (n.controlName && n.controlName !== '—'
            ? '<div style="display:flex;align-items:center;gap:0.35rem;margin-top:0.2rem;padding-left:5.95rem">' +
                '<span style="font-size:0.67rem;color:var(--muted)">&#11042;</span>' +
                '<span style="font-size:0.68rem;color:' + vc + ';font-weight:500">' + x(n.controlName) + '</span>' +
                (n.alertName ? '<span style="font-size:0.64rem;color:var(--muted)">&#183; ' + x(n.alertName) + '</span>' : '') +
                (n.durationMs ? '<span style="font-size:0.62rem;color:var(--muted);margin-left:auto">&#8764;' + n.durationMs + 'ms</span>' : '') +
              '</div>'
            : (n.durationMs ? '<div style="text-align:right;font-size:0.62rem;color:var(--muted);margin-top:0.15rem">&#8764;' + n.durationMs + 'ms</div>' : '')) +
          (n.isStopPoint
            ? '<div style="margin-top:0.25rem;padding-left:5.95rem;font-size:0.67rem;color:var(--success);font-weight:600">&#9940; Attack stopped here</div>'
            : '') +
        '</div>';
    });

    // Connector between phases (only when the attack continued past this phase)
    if (pi < phases.length - 1) {
      var phaseBlocked = phase.nodes.some(function(n) { return n.isStopPoint; });
      var connColor = phaseBlocked ? 'rgba(210,153,34,0.4)' : 'rgba(218,54,51,0.35)';
      var connLabel = phaseBlocked ? 'Partially blocked — attack continued' : 'Attack progressed';
      flowHtml +=
        '<div style="display:flex;align-items:center;gap:0.5rem;margin:0.45rem 0;padding:0 0.2rem">' +
          '<div style="flex:1;height:1px;background:' + connColor + '"></div>' +
          '<span style="font-size:0.6rem;color:var(--muted);white-space:nowrap">' + connLabel + '</span>' +
          '<div style="flex:1;height:1px;background:' + connColor + '"></div>' +
        '</div>';
    }
  });

  return summaryHtml + flowHtml;
}

// Renders the dual-rail kill-chain step nodes from rep.killChain. Shared by the
// run drawer and the dashboard Attack-flow card so both rails stay identical.
export function killChainNodes(kc) {
  kc = kc || [];
  var kcOut = { prevented:{cls:'def-prevented',l:'Prevented'}, detected:{cls:'def-detected',l:'Detected'}, missed:{cls:'def-missed',l:'Missed'} };
  return kc.map(function(s, i) {
    var o = kcOut[s.outcome] || kcOut.missed;
    var lbl = o.l;
    if (s.outcome === 'detected' && s.confidence) lbl += ' · ' + s.confidence;
    var defText = x(s.detail || o.l);
    if (s.outcome === 'detected' && s.latencyMs) defText += ' (' + Math.round(s.latencyMs / 1000) + 's)';
    var conn = i < kc.length - 1 ? '<div class="kc-conn">&rarr;</div>' : '';
    return '<div class="kc-step">' +
      '<div class="kc-phase">' + x((s.phase || '').replace(/-/g, ' ')) + '</div>' +
      '<div class="kc-rail"></div>' +
      '<div class="kc-node">' +
        (s.techniqueId ? '<div class="kc-tech">' + x(s.techniqueId) + '</div>' : '') +
        '<div class="kc-name">' + x(s.technique || '—') + '</div>' +
        '<div class="kc-rails">' +
          '<div class="kc-r atk"><span class="ri"></span>' + x(s.action || 'Executed') + '</div>' +
          '<div class="kc-r ' + o.cls + '"><span class="ri"></span>' + defText + '<span class="rv">' + x(lbl) + '</span></div>' +
        '</div>' +
      '</div>' + conn +
    '</div>';
  }).join('');
}

// Builds the Overview tab's report-engine dashboard panels (attack flow kill
// chain, alert fatigue, attack surface age, endpoint stability, environment
// restoration, detection coverage) from the report-engine payload. Key
// Findings and Prioritised Recommendations moved to their own tabs — see
// renderRunFindings / renderRunRecommendations below.
export function renderRunReportExtra(rep) {
  rep = rep || {};
  var panel = 'background:var(--elevated);border:1px solid var(--border);border-radius:4px;padding:0.6rem 0.75rem;margin-bottom:0.75rem';
  var hdr = 'font-size:0.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin-bottom:0.45rem';
  var html = '';

  // Dual-rail kill chain — each adversary action paired with the defensive
  // outcome (Prevented / Detected / Missed), ordered by ATT&CK kill-chain phase.
  // The signature purple-team timeline; sourced from rep.killChain (BuildFromRun).
  var kc = rep.killChain || [];
  if (kc.length > 0) {
    var nodes = killChainNodes(kc);
    html += '<div style="' + panel + '">' +
      '<div style="' + hdr + ';display:flex;align-items:center;gap:10px">Attack Flow &mdash; Adversary vs Defense' +
        '<span style="margin-left:auto;display:flex;gap:9px;font-weight:400;text-transform:none;letter-spacing:0">' +
          '<span style="font-size:0.6rem;color:#5cead8">&#9632; Prevented</span>' +
          '<span style="font-size:0.6rem;color:#e6c069">&#9632; Detected</span>' +
          '<span style="font-size:0.6rem;color:var(--muted)">&#9632; Missed</span>' +
        '</span></div>' +
      // .killchain's steps are min-width:178px each and don't wrap by design
      // (it's a horizontal timeline) -- scope the horizontal scroll to just
      // this element instead of letting it force the whole drawer to scroll.
      '<div style="overflow-x:auto"><div class="killchain">' + nodes + '</div></div></div>';
  }

  // Alert Fatigue & Noise Score
  if (typeof rep.alertsTotal !== 'undefined') {
    var total = rep.alertsTotal || 0;
    var high = rep.alertsHighFidelity || 0;
    var noise = rep.noiseScore || 0;
    var alertDesc = "";
    if (total > 0) {
      if (high > 0) {
        alertDesc = "Simulation generated <strong>" + total + " alerts</strong> (<strong>" + high + " high-fidelity</strong>).";
      } else {
        alertDesc = "Simulation generated <strong>" + total + " alerts</strong> (<strong>0 high-fidelity</strong>).";
      }
    } else {
      alertDesc = "No alerts generated during the simulation.";
    }

    var noiseCol = noise >= 75 ? 'var(--danger)' : noise >= 40 ? 'var(--warning)' : 'var(--success)';

    html += '<div style="' + panel + ';border-left:3px solid ' + noiseCol + '">' +
      '<div style="' + hdr + '">Alert Fatigue &amp; Noise Analysis</div>' +
      '<div style="display:flex;align-items:center;justify-content:space-between;gap:1rem">' +
        '<div>' +
          '<div style="font-size:0.82rem;color:var(--text);margin-bottom:0.25rem">' + alertDesc + '</div>' +
          '<div style="font-size:0.7rem;color:var(--muted)">SOC teams care about alert fatigue. High noise ratios degrade investigation SLA.</div>' +
        '</div>' +
        '<div style="text-align:right;min-width:85px">' +
          '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.1rem">Noise Score</div>' +
          '<div style="font-size:1.3rem;font-weight:700;color:' + noiseCol + '">' + Math.round(noise) + '%</div>' +
        '</div>' +
      '</div>' +
    '</div>';
  }

  // Attack Surface Age
  if (typeof rep.attackSurfaceAge !== 'undefined') {
    var age = rep.attackSurfaceAge || 0;
    var oldestID = rep.oldestFindingID || '';
    var oldestName = rep.oldestFindingName || '';
    var oldestSev = rep.oldestFindingSeverity || '';
    var sla = rep.attackSurfaceSLAStatus || 'within-sla';
    
    var slaCol = sla === 'critical-sla' ? 'var(--danger)' : sla === 'over-sla' ? 'var(--warning)' : 'var(--success)';
    var slaLabel = sla === 'critical-sla' ? 'CRITICAL SLA' : sla === 'over-sla' ? 'OVER SLA' : 'WITHIN SLA';
    
    var ageDesc = "";
    if (oldestID) {
      ageDesc = 'Exposed weakness present for <strong>' + age + ' days</strong>.<br/>' +
                '<span style="font-size:0.72rem;color:var(--muted)">Oldest weakness: <strong>' + x(oldestID) + '</strong> (' + x(oldestName) + ') &middot; Severity: <strong>' + x(oldestSev) + '</strong></span>';
    } else {
      ageDesc = 'No open weaknesses detected on this agent.';
    }

    html += '<div style="' + panel + ';border-left:3px solid ' + slaCol + '">' +
      '<div style="' + hdr + '">Attack Surface Age</div>' +
      '<div style="display:flex;align-items:center;justify-content:space-between;gap:1rem">' +
        '<div>' +
          '<div style="font-size:0.82rem;color:var(--text);margin-bottom:0.25rem">' + ageDesc + '</div>' +
        '</div>' +
        '<div style="text-align:right;min-width:105px">' +
          '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.1rem">' + slaLabel + '</div>' +
          '<div style="font-size:1.15rem;font-weight:700;color:' + slaCol + '">' + age + ' Days</div>' +
        '</div>' +
      '</div>' +
    '</div>';
  }

  // Endpoint Stability Check
  if (typeof rep.perfCpuBefore !== 'undefined') {
    var cpuB = rep.perfCpuBefore || 2.4;
    var cpuA = rep.perfCpuAfter || 2.6;
    var ramB = rep.perfRamBefore || 5.1;
    var ramA = rep.perfRamAfter || 5.1;
    var diskB = rep.perfDiskBefore || 61.2;
    var diskA = rep.perfDiskAfter || 61.2;

    html += '<div style="' + panel + ';border-left:3px solid var(--success)">' +
      '<div style="' + hdr + '">Endpoint Stability Check</div>' +
      '<div style="display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap">' +
        '<div style="display:flex;gap:1.5rem">' +
          '<div>' +
            '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.1rem">Before Running</div>' +
            '<div style="font-size:0.78rem;color:var(--text)">CPU: <strong>' + cpuB.toFixed(1) + '%</strong> &middot; RAM: <strong>' + ramB.toFixed(1) + ' GB</strong> &middot; Disk: <strong>' + diskB.toFixed(1) + '%</strong></div>' +
          '</div>' +
          '<div>' +
            '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.1rem">After Running</div>' +
            '<div style="font-size:0.78rem;color:var(--text)">CPU: <strong>' + cpuA.toFixed(1) + '%</strong> &middot; RAM: <strong>' + ramA.toFixed(1) + ' GB</strong> &middot; Disk: <strong>' + diskA.toFixed(1) + '%</strong></div>' +
          '</div>' +
        '</div>' +
        '<div style="text-align:right;min-width:110px">' +
          '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.1rem">Health Impact</div>' +
          '<div style="font-size:1.1rem;font-weight:700;color:var(--success)">Negligible</div>' +
        '</div>' +
      '</div>' +
    '</div>';
  }

  // Environment Restoration (replaces old cleanup banner — uses envRestoration when available)
  var envR = rep.envRestoration || null;
  var hasOldCleanup = (rep.reverted && rep.reverted.length > 0) || rep.cleanupFailed;
  if (envR || hasOldCleanup) {
    var erLevel  = envR ? envR.impactLevel  : (rep.cleanupFailed ? 'persistent' : 'clean');
    var erStatus = envR ? envR.statusLabel  : (rep.cleanupFailed ? 'Attention Required' : 'Successful');
    var erLabel  = envR ? envR.impactLabel  : (rep.cleanupFailed ? 'Residual Changes (' + (rep.cleanupFailedCount || 1) + ')' : 'No Persistent Changes');
    var erRate   = envR ? envR.cleanupRate  : (rep.cleanupFailed ? 0 : 100);
    var erLeaked = envR ? envR.stepsLeaked  : (rep.cleanupFailedCount || 0);
    var erCleaned= envR ? envR.stepsCleaned : 0;
    var erSummary= envR ? envR.execSummary  : (rep.cleanupFailed
      ? (rep.cleanupFailedCount || 1) + ' step(s) did not revert cleanly. Manual remediation may be required.'
      : 'All simulation-induced changes were reverted successfully.');

    var erBorderCol = erLevel === 'clean' ? 'var(--success)' : erLevel === 'minor' ? 'var(--warning)' : 'var(--danger)';
    var erTextCol   = erLevel === 'clean' ? '#15803d' : erLevel === 'minor' ? '#92400e' : '#991b1b';
    var erBg        = erLevel === 'clean' ? 'rgba(13,148,136,0.07)' : erLevel === 'minor' ? 'rgba(210,153,34,0.1)' : 'rgba(218,54,51,0.08)';
    var erIcon      = erLevel === 'clean' ? '&#10003;' : erLevel === 'minor' ? '&#9888;' : '&#10007;';

    var erItemsHtml = '';
    if (rep.reverted && rep.reverted.length > 0) {
      erItemsHtml = '<div style="font-size:0.6rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-top:0.6rem;margin-bottom:0.35rem">Agent-Confirmed Rollbacks (' + rep.reverted.length + ')</div>' +
        '<div style="max-height:100px;overflow-y:auto;background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:0.4rem 0.5rem;font-family:monospace;font-size:0.72rem;color:var(--text);line-height:1.4">' +
          rep.reverted.map(function(item) {
            return '<div style="margin-bottom:0.15rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis" title="' + x(item) + '">&bull; ' + x(item) + '</div>';
          }).join('') +
        '</div>';
    }

    // Leaked-item detail: the aggregate "N step(s) leaked" line above can't
    // say WHICH step, WHAT's still on the endpoint, or WHY the cleanup
    // script didn't remove it -- envR.leakedItems (internal/reporting's
    // LeakedCleanupItem) carries exactly that, one entry per non-rescued
    // partial/leaked step.
    var erLeakedHtml = '';
    if (envR && envR.leakedItems && envR.leakedItems.length > 0) {
      erLeakedHtml = '<div style="font-size:0.6rem;color:var(--danger);text-transform:uppercase;letter-spacing:.06em;margin-top:0.6rem;margin-bottom:0.35rem">Residual Changes (' + envR.leakedItems.length + ')</div>' +
        '<div style="background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:0.5rem 0.6rem;font-size:0.72rem;color:var(--text);line-height:1.5">' +
          envR.leakedItems.map(function(item) {
            var title = x(item.techniqueId) + (item.stepName ? ' — ' + x(item.stepName) : '') + (item.techniqueName ? ' (' + x(item.techniqueName) + ')' : '');
            var residualLine = (item.residual && item.residual.length > 0)
              ? '<div style="color:var(--warning);margin-top:2px">Left on endpoint: <code>' + x(item.residual.join(', ')) + '</code></div>'
              : '';
            var errorLine = item.error
              ? '<div style="color:var(--muted);margin-top:2px;font-family:monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis" title="' + x(item.error) + '">Cleanup error: ' + x(item.error) + '</div>'
              : '';
            return '<div style="margin-bottom:0.5rem;padding-bottom:0.5rem;border-bottom:1px solid rgba(34,50,74,0.4)">' +
              '<div class="u-fw600">' + title + ' <span style="font-weight:400;color:var(--muted);text-transform:capitalize">(' + x(item.verdict) + ')</span></div>' +
              residualLine + errorLine +
            '</div>';
          }).join('') +
        '</div>';
    }

    html += '<div style="' + panel + ';border-left:3px solid ' + erBorderCol + ';background:' + erBg + '">' +
      '<div style="' + hdr + ';display:flex;align-items:center;justify-content:space-between">' +
        '<span>Environment Restoration</span>' +
        '<span style="font-size:0.58rem;font-weight:700;color:' + erTextCol + '">' + x(erStatus.toUpperCase()) + '</span>' +
      '</div>' +
      '<div style="display:flex;align-items:flex-start;gap:12px;margin-bottom:0.5rem">' +
        '<div style="font-size:1.8rem;line-height:1;color:' + erTextCol + ';flex-shrink:0">' + erIcon + '</div>' +
        '<div class="u-flex1">' +
          '<div style="font-size:0.92rem;font-weight:700;color:' + erTextCol + '">' + erRate.toFixed(1) + '% Clean &mdash; ' + x(erLabel) + '</div>' +
          '<div style="font-size:0.75rem;color:var(--text);margin-top:3px;line-height:1.4">' + x(erSummary) + '</div>' +
        '</div>' +
        '<div style="text-align:right;flex-shrink:0">' +
          '<div style="font-size:0.58rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:2px">Cleanup Rate</div>' +
          '<div style="font-size:1.4rem;font-weight:800;color:' + erBorderCol + '">' + Math.round(erRate) + '%</div>' +
        '</div>' +
      '</div>' +
      (erLeaked > 0 ? '<div style="font-size:0.72rem;color:var(--danger);margin-bottom:4px">&#9888; ' + erLeaked + ' step(s) leaked &nbsp;&#8226;&nbsp; ' + erCleaned + ' cleaned</div>' : '') +
      (envR && envR.stepsRescued > 0 ? '<div style="font-size:0.72rem;color:var(--warning);margin-bottom:4px">&#9888; ' + envR.stepsRescued + ' step(s) cleaned by the safety-net sweep, not by their own script</div>' : '') +
      erLeakedHtml +
      erItemsHtml +
    '</div>';
  }

  // Detection coverage — purple-team verdicts from the agent's post-run alert
  // sweep, correlated server-side. Empty until detections are submitted; the most
  // valuable BAS metric here is Undetected Rate (succeeded with NO alert = blind spot).
  var sum = rep.summary || {};
  var dTechs = rep.detectionTechniques || [];
  if (typeof sum.detectionRate !== 'undefined' && (dTechs.length > 0 || sum.detectionRate || sum.undetectedRate)) {
    var dimStyle2 = 'background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:0.55rem 0.7rem';
    var labelStyle2 = 'color:var(--muted);font-size:0.6rem;text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.2rem';
    var bigStyle2 = 'font-size:1.3rem;font-weight:700;line-height:1.1';
    var detCol = sum.detectionRate >= 70 ? 'var(--success)' : sum.detectionRate >= 40 ? 'var(--warning)' : 'var(--danger)';
    var undCol = sum.undetectedRate <= 20 ? 'var(--success)' : sum.undetectedRate <= 50 ? 'var(--warning)' : 'var(--danger)';
    var nCards = 2;
    var cards =
      '<div style="' + dimStyle2 + '"><div style="' + labelStyle2 + '">Detection Rate</div>' +
        '<div style="' + bigStyle2 + ';color:' + detCol + '">' + (sum.detectionRate || 0) + '%</div>' +
        '<div style="font-size:0.62rem;color:var(--muted);margin-top:0.1rem">of executed, not prevented</div></div>' +
      '<div style="' + dimStyle2 + '"><div style="' + labelStyle2 + '">Undetected</div>' +
        '<div style="' + bigStyle2 + ';color:' + undCol + '">' + (sum.undetectedRate || 0) + '%</div>' +
        '<div style="font-size:0.62rem;color:var(--muted);margin-top:0.1rem">succeeded, no alert — blind spot</div></div>';
    // Logged: an alert landed in the window but nothing attributed it to a
    // control. Without this tile the two rates above stop summing to 100 with
    // no explanation, which reads as a bug rather than as the honest gap it is.
    if (sum.logged) {
      cards += '<div style="' + dimStyle2 + '"><div style="' + labelStyle2 + '">Logged</div>' +
        '<div style="' + bigStyle2 + ';color:var(--warning)">' + (sum.loggedRate || 0) + '%</div>' +
        '<div style="font-size:0.62rem;color:var(--muted);margin-top:0.1rem">activity in window, not attributed</div></div>';
      nCards++;
    }
    if (sum.mttdMs) {
      cards += '<div style="' + dimStyle2 + '"><div style="' + labelStyle2 + '">MTTD</div>' +
        '<div style="' + bigStyle2 + ';color:var(--text)">' + Math.round(sum.mttdMs / 1000) + 's</div>' +
        '<div style="font-size:0.62rem;color:var(--muted);margin-top:0.1rem">mean time to detect</div></div>';
      nCards++;
    }
    var detHtml = '<div style="' + panel + '"><div style="' + hdr + '">Detection Coverage</div>' +
      '<div style="display:grid;grid-template-columns:repeat(' + nCards + ',1fr);gap:0.5rem">' + cards + '</div>';

    if (dTechs.length > 0) {
      var rows2 = dTechs.map(function(d) {
        var bg, fg, lbl;
        if (d.verdict === 'prevented') { bg = 'rgba(47,216,195,0.15)'; fg = 'var(--teal)'; lbl = 'Prevented'; }
        else if (d.verdict === 'detected') {
          var hi = (d.confidence === 'high');
          bg = hi ? 'rgba(47,129,247,0.15)' : 'rgba(210,153,34,0.15)';
          fg = hi ? 'var(--accent)' : 'var(--warning)';
          lbl = 'Detected' + (d.confidence ? ' · ' + d.confidence : '');
        } else { bg = 'rgba(218,54,51,0.15)'; fg = 'var(--danger)'; lbl = '⚠ Undetected'; }
        var ttd = (d.verdict === 'detected' && d.timeToDetectMs) ? '<span style="font-size:0.62rem;color:var(--muted);margin-left:auto">' + Math.round(d.timeToDetectMs / 1000) + 's</span>' : '';
        return '<div style="display:flex;align-items:center;gap:0.5rem;padding:0.28rem 0;border-bottom:1px solid rgba(34,50,74,0.45)">' +
          '<code style="font-size:0.68rem;color:var(--muted);min-width:88px">' + x(d.techniqueId || '—') + '</code>' +
          '<span style="font-size:0.62rem;font-weight:700;text-transform:capitalize;background:' + bg + ';color:' + fg + ';border-radius:3px;padding:1px 7px">' + x(lbl) + '</span>' +
          ttd +
        '</div>';
      }).join('');
      detHtml += '<div class="u-mt-06">' + rows2 + '</div>';
    }

    if (rep.detectionSources && rep.detectionSources.length > 0) {
      var dsRows = rep.detectionSources.map(function(ds, idx) {
        var minTtd = ds.minMttdMs ? Math.round(ds.minMttdMs / 1000) + 's' : '—';
        var avgTtd = ds.avgMttdMs ? Math.round(ds.avgMttdMs / 1000) + 's' : '—';
        return '<tr style="border-bottom:1px solid rgba(255,255,255,0.05)">' +
          '<td style="padding:0.4rem 0.2rem;font-size:0.75rem;color:var(--muted)">#' + (idx + 1) + '</td>' +
          '<td style="padding:0.4rem 0.2rem;font-size:0.75rem;font-weight:600">' + x(ds.product) + '</td>' +
          '<td style="padding:0.4rem 0.2rem;font-size:0.75rem;text-align:right;font-weight:700;color:var(--success)">' + ds.detections + '</td>' +
          '<td style="padding:0.4rem 0.2rem;font-size:0.75rem;text-align:right">' + minTtd + '</td>' +
          '<td style="padding:0.4rem 0.2rem;font-size:0.75rem;text-align:right;color:var(--muted)">' + avgTtd + '</td>' +
        '</tr>';
      }).join('');

      detHtml += '<div style="margin-top:1rem;border-top:1px solid var(--border);padding-top:0.8rem">' +
        '<div style="font-size:0.65rem;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:0.4rem;font-weight:600">Detection Source Ranking</div>' +
        '<table style="width:100%;border-collapse:collapse">' +
          '<thead>' +
            '<tr style="border-bottom:1.5px solid var(--border)">' +
              '<th style="text-align:left;padding-bottom:0.2rem;font-size:0.62rem;color:var(--muted);text-transform:uppercase">Rank</th>' +
              '<th style="text-align:left;padding-bottom:0.2rem;font-size:0.62rem;color:var(--muted);text-transform:uppercase">Product</th>' +
              '<th style="text-align:right;padding-bottom:0.2rem;font-size:0.62rem;color:var(--muted);text-transform:uppercase">Detections</th>' +
              '<th style="text-align:right;padding-bottom:0.2rem;font-size:0.62rem;color:var(--muted);text-transform:uppercase">Min TTD</th>' +
              '<th style="text-align:right;padding-bottom:0.2rem;font-size:0.62rem;color:var(--muted);text-transform:uppercase">Avg TTD</th>' +
            '</tr>' +
          '</thead>' +
          '<tbody>' + dsRows + '</tbody>' +
        '</table>' +
      '</div>';
    }

    detHtml += '</div>';
    html += detHtml;
  }

  return html;
}

// Key Findings — its own full-width tab (run-tab-findings). Previously this
// list lived inside the 340px Overview side rail alongside scorePanel; a run
// with many findings made that rail scroll far past the short left column,
// leaving it blank. A dedicated tab with a card grid gives it room to breathe.
export function renderRunFindings(rep) {
  rep = rep || {};
  var findings = rep.topFindings || [];
  if (!findings.length) {
    return '<div style="color:var(--muted);font-size:0.8rem;padding:2.5rem 0;text-align:center">No findings recorded for this run.</div>';
  }
  var cards = findings.map(function(f, i) {
    var sc = f.severity === 'Critical' ? 'var(--danger)' : f.severity === 'High' ? '#e5534b' : 'var(--warning)';
    var num = 'F-' + ('0' + (i + 1)).slice(-2);
    return '<div class="dash-panel" style="border-left:3px solid ' + sc + ';padding:0.9rem 1rem">' +
      '<div style="display:flex;align-items:baseline;gap:0.5rem;flex-wrap:wrap;margin-bottom:0.4rem">' +
        '<span style="color:' + sc + ';font-weight:700;font-size:0.66rem;text-transform:uppercase;letter-spacing:.04em">' + x(f.severity || '') + '</span>' +
        '<span style="font-size:0.62rem;color:var(--muted)">' + num + '</span>' +
        (f.techniqueId ? '<code style="font-size:0.7rem;color:var(--muted)">' + x(f.techniqueId) + '</code>' : '') +
        '<span style="font-size:0.68rem;color:var(--muted);margin-left:auto;text-transform:capitalize">' + x((f.tactic || '').replace(/-/g, ' ')) + '</span>' +
      '</div>' +
      '<div style="font-size:0.92rem;font-weight:600;margin-bottom:0.35rem">' + x(f.techniqueName || '') + '</div>' +
      (f.details ? '<div style="color:var(--muted);font-size:0.8rem;line-height:1.55">' + x(f.details) + '</div>' : '') +
      (f.remediation ? '<div style="color:var(--warning);font-size:0.78rem;margin-top:0.5rem;padding-top:0.5rem;border-top:1px solid var(--border);white-space:pre-wrap"><strong>Remediation:</strong> ' + x(f.remediation) + '</div>' : '') +
    '</div>';
  }).join('');
  return '<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:0.85rem">' + cards + '</div>';
}

// Prioritised Recommendations — its own full-width tab (run-tab-recommendation),
// replacing what used to be a permanent "coming soon" placeholder even though
// this data has been available all along (it just lived in the Overview rail).
export function renderRunRecommendations(rep) {
  rep = rep || {};
  var recs = rep.recommendations || [];
  if (!recs.length) {
    return '<div style="color:var(--muted);font-size:0.8rem;padding:2.5rem 0;text-align:center">No recommendations for this run.</div>';
  }
  var items = recs.map(function(rc, i) {
    return '<div class="dash-panel" style="display:flex;gap:0.9rem;align-items:flex-start;padding:0.85rem 1rem">' +
      '<div style="flex-shrink:0;width:26px;height:26px;border-radius:50%;background:var(--accent-dim);color:var(--accent);display:flex;align-items:center;justify-content:center;font-size:0.72rem;font-weight:700">' + (i + 1) + '</div>' +
      '<div style="font-size:0.86rem;line-height:1.6;padding-top:0.2rem">' + x(rc) + '</div>' +
    '</div>';
  }).join('');
  return '<div style="display:flex;flex-direction:column;gap:0.6rem;max-width:900px">' + items + '</div>';
}