package rulelib

import (
	"embed"
	"encoding/json"
	"log"
)

//go:embed ruledata/rules.json ruledata/metadata.json
var ruledataFS embed.FS

// currentSchemaVersion is the metadata.schemaVersion this binary understands.
// A mismatch means the embedded bundle was generated by an incompatible
// generator — the engine loads empty rather than risk serving malformed data.
const currentSchemaVersion = 1

// Engine holds the loaded rule library in memory. Safe for concurrent read
// access after construction (never mutated post-NewEngine).
type Engine struct {
	rules    []Rule
	metadata Metadata
	idx      indexes
}

// NewEngine loads the embedded rule bundle. On any parse failure or schema
// version mismatch, it logs a warning and returns an engine with zero rules
// — the rule library silently disables rather than blocking orchestrator
// startup (matches the nil-safe-resolver pattern used elsewhere in this
// codebase, e.g. reporting.Engine's ScenarioResolver/VerificationResolver).
func NewEngine() *Engine {
	metaRaw, err := ruledataFS.ReadFile("ruledata/metadata.json")
	if err != nil {
		log.Printf("[rulelib] read metadata.json: %v — rule library disabled", err)
		return &Engine{}
	}
	rulesRaw, err := ruledataFS.ReadFile("ruledata/rules.json")
	if err != nil {
		log.Printf("[rulelib] read rules.json: %v — rule library disabled", err)
		return &Engine{}
	}
	return loadFromBytes(rulesRaw, metaRaw)
}

// loadFromBytes is NewEngine's parsing logic, factored out so tests can
// exercise the degradation paths without depending on go:embed's
// compile-time-fixed file set.
func loadFromBytes(rulesRaw, metaRaw []byte) *Engine {
	var meta Metadata
	if err := json.Unmarshal(metaRaw, &meta); err != nil {
		log.Printf("[rulelib] parse metadata.json: %v — rule library disabled", err)
		return &Engine{}
	}
	if meta.SchemaVersion != currentSchemaVersion {
		log.Printf("[rulelib] embedded schemaVersion %d != supported %d — rule library disabled",
			meta.SchemaVersion, currentSchemaVersion)
		return &Engine{}
	}
	var rules []Rule
	if err := json.Unmarshal(rulesRaw, &rules); err != nil {
		log.Printf("[rulelib] parse rules.json: %v — rule library disabled", err)
		return &Engine{}
	}
	return &Engine{rules: rules, metadata: meta, idx: buildIndexes(rules)}
}

func (e *Engine) RuleCount() int     { return len(e.rules) }
func (e *Engine) Metadata() Metadata { return e.metadata }
