#!/usr/bin/env bash
# BAS Platform — RSA-4096 License Key Generator
#
# Run ONCE on your build machine. Store private.pem securely — never commit it.
# After running, rebuild the Docker image so the new public key is embedded.
#
# Usage (from repo root in Git Bash):
#   bash packaging/licensing/keygen.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
KEYS_DIR="${SCRIPT_DIR}/keys"
LICENSE_KEY_GO="${REPO_ROOT}/orchestrator/internal/license/license_key.go"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }

if ! command -v openssl &>/dev/null; then
  err "openssl not found. Run this in Git Bash (Windows) or a Linux shell."
  exit 1
fi

mkdir -p "${KEYS_DIR}"
chmod 700 "${KEYS_DIR}" 2>/dev/null || true

if [[ -f "${KEYS_DIR}/private.pem" ]]; then
  warn "private.pem already exists."
  warn "Delete ${KEYS_DIR}/private.pem first if you really want to regenerate."
  warn "Regenerating invalidates all previously issued licenses."
  exit 1
fi

log "Generating RSA-4096 key pair (this takes a moment)..."
openssl genrsa -out "${KEYS_DIR}/private.pem" 4096 2>/dev/null
chmod 600 "${KEYS_DIR}/private.pem" 2>/dev/null || true
log "  Private key: ${KEYS_DIR}/private.pem"

openssl rsa -in "${KEYS_DIR}/private.pem" -pubout -out "${KEYS_DIR}/public.pem" 2>/dev/null
log "  Public key:  ${KEYS_DIR}/public.pem"

# Write the public key into the Go constant that gets embedded in the binary.
# Use a raw string literal (backticks) — avoids any quoting/escaping issues.
{
  echo 'package license'
  echo ''
  echo '// PublicKeyPEM is the Audspect RSA-4096 public key embedded at build time.'
  echo '// Generated by packaging/licensing/keygen.sh — do NOT edit manually.'
  echo '// Regenerate only if the private key is compromised (invalidates all licenses).'
  printf 'var PublicKeyPEM = `'
  cat "${KEYS_DIR}/public.pem"
  printf '`\n'
} > "${LICENSE_KEY_GO}"

log "  Embedded public key → ${LICENSE_KEY_GO}"

echo ""
warn "=================================================================="
warn "  BACK UP ${KEYS_DIR}/private.pem immediately."
warn "  It is gitignored. Losing it means you cannot issue new licenses."
warn "=================================================================="
echo ""
log "Next steps:"
echo "  1. Rebuild Docker image:  docker build -t bas-orchestrator:VERSION ..."
echo "  2. Issue a license:       go run packaging/licensing/licensegen/main.go \\"
echo "         -customer 'Client Name' -id client-001 -days 365 \\"
echo "         -key packaging/licensing/keys/private.pem"
echo "  3. Send client:           <client-id>.lic"
echo "  4. Client config:         BAS_LICENSE_PATH=/etc/bas/bas.lic"
