package integrity

import (
	"crypto"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
)

// ScenarioPublicKeyPEM is the Audspect RSA-4096 public key used to verify
// builtin scenario YAML files and the BINARIES.sha256 manifest.
// Generated by packaging/signing/keygen.sh — do NOT edit manually.
// When set to the placeholder "SIGNING_KEYGEN_REQUIRED", signature
// verification is disabled (development / pre-release builds only).
var ScenarioPublicKeyPEM = `-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAriWUu8PCVZCg58jfW5nq
QC5TKgimjz4GAjmmdLqGR9y9Wgix5+6pw+V/i2QOYWaj8WhM+Y2gCbbeSUWIdnCp
TY/G9BM5tn4FyHxoPFdZi0FDzfGcJJ0+p+5NSjlj8KcY3LJGxPCqMOmKUwnIinHw
IaHcglDwCeRhZ/5+1gg3SkEFExEx6fT7b7EpFqzecLXwyiPs/nMbsgoVEI91Oijv
ZFI8xjNBr2sY8YtAk7yl7ywPfGuiv5pLHdy2xMEHwGbhlSsaQJF6w4ERVsSaoUz/
Z2DPpVznA1Q5My33dedKupBXr4EMGc6gxOF+fhdF0aGOw5QuS1mbsGxxiue9Bb3m
8uQuJpW+wA6Y7me76Jx5CkMbbvRWsYYLlkuaXRYhZa08dUcOv38aRvRkerpGOhWU
N89t2d6cs0Ld1UaxWZhpnTRxlZF2c/cB4THVnRP76L/JFUb7RC3FdWrAvUrFq/jp
Wwz8eOPsJ9iMn6Qzcfl1diYymuONS0nUNBDI3fqLSakFdD9srdJNERN8zGuxe+/i
Mf8mtdZ0JjJEdSPpsDvySJQyTKlHpSqIlvCJy2e0Qx1+Kab2MWR/ni5JslFI/9ym
DAzhofGd3OuhbUbSYf8aKPsNZ1NjXl357f/PJNSeUcyaBeGnpFWkLz5GpgPBYovN
Ae7AJBFEx96f0Wev7nmqQbMCAwEAAQ==
-----END PUBLIC KEY-----
`

// parseContentPublicKey parses ScenarioPublicKeyPEM into an *rsa.PublicKey.
func parseContentPublicKey() (*rsa.PublicKey, error) {
	block, _ := pem.Decode([]byte(ScenarioPublicKeyPEM))
	if block == nil {
		return nil, errors.New("failed to decode PEM block")
	}
	key, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, err
	}
	pub, ok := key.(*rsa.PublicKey)
	if !ok {
		return nil, errors.New("not an RSA public key")
	}
	return pub, nil
}

// signingEnabled returns true when a real public key has been compiled in.
func signingEnabled() bool {
	return ScenarioPublicKeyPEM != "SIGNING_KEYGEN_REQUIRED"
}

// ─── Scenario YAML verification ──────────────────────────────────────────────

// VerifyScenarioFile verifies that the YAML file at path has a valid RSA-SHA256
// signature in the adjacent path+".sig" file.
//
// Rules:
//   - If ScenarioPublicKeyPEM is the placeholder, verification is skipped (dev builds).
//   - If the .sig file is absent, the scenario is rejected with ErrUnsigned.
//   - If the signature is invalid, the scenario is rejected with a wrapped error.
func VerifyScenarioFile(path string) error {
	if !signingEnabled() {
		return nil // dev/pre-release build — skip
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read scenario: %w", err)
	}

	sigRaw, err := os.ReadFile(path + ".sig")
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("%w: %s", ErrUnsigned, path)
		}
		return fmt.Errorf("read .sig: %w", err)
	}

	sigBytes, err := base64.StdEncoding.DecodeString(string(sigRaw))
	if err != nil {
		return fmt.Errorf("decode signature: %w", err)
	}

	pub, err := parseContentPublicKey()
	if err != nil {
		return fmt.Errorf("content public key: %w", err)
	}

	hash := sha256.Sum256(content)
	if err := rsa.VerifyPKCS1v15(pub, crypto.SHA256, hash[:], sigBytes); err != nil {
		return fmt.Errorf("scenario signature invalid for %s — file may be tampered: %w", path, err)
	}
	return nil
}

// ErrUnsigned is returned when a builtin scenario has no .sig file at all.
var ErrUnsigned = errors.New("unsigned builtin scenario")

// ─── Manifest verification ────────────────────────────────────────────────────

// LoadManifestVerified loads the BINARIES.sha256 manifest and verifies it
// against an adjacent BINARIES.sha256.sig signature file.
//
//   - If ScenarioPublicKeyPEM is the placeholder, falls back to LoadManifest
//     (no verification — dev builds only).
//   - If the manifest or .sig file is absent, returns an empty manifest
//     (hash verification disabled) — same behaviour as LoadManifest when the
//     file does not exist.
//   - If the signature check fails, returns a fatal error so main() can halt
//     with log.Fatalf: a tampered manifest must never be trusted.
func LoadManifestVerified(path string) (*Manifest, error) {
	if !signingEnabled() {
		// Dev build — fall back to unsigned load.
		return LoadManifest(path), nil
	}

	// Read manifest content first; absence is not an error (verification disabled).
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Manifest{hashes: make(map[string]string)}, nil
		}
		return nil, fmt.Errorf("manifest read: %w", err)
	}

	// Read signature. Absent .sig means the build skipped signing — degrade
	// gracefully (hash verification disabled) rather than refusing to start.
	sigRaw, err := os.ReadFile(path + ".sig")
	if err != nil {
		if os.IsNotExist(err) {
			return &Manifest{hashes: make(map[string]string)}, nil
		}
		return nil, fmt.Errorf("manifest .sig read: %w", err)
	}

	sigBytes, err := base64.StdEncoding.DecodeString(string(sigRaw))
	if err != nil {
		return nil, fmt.Errorf("manifest signature decode: %w", err)
	}

	pub, err := parseContentPublicKey()
	if err != nil {
		return nil, fmt.Errorf("content public key: %w", err)
	}

	hash := sha256.Sum256(content)
	if err := rsa.VerifyPKCS1v15(pub, crypto.SHA256, hash[:], sigBytes); err != nil {
		return nil, errors.New("BINARIES.sha256 signature verification FAILED — manifest may be tampered")
	}

	// Signature valid — now parse the (already-read) content.
	m := &Manifest{hashes: make(map[string]string)}
	for _, line := range splitLines(string(content)) {
		if line == "" || line[0] == '#' {
			continue
		}
		parts := splitFields(line)
		if len(parts) < 2 {
			continue
		}
		filename := trimPrefix(parts[1], "./")
		m.hashes[filename] = toLower(parts[0])
	}
	return m, nil
}

// ── minimal string helpers to avoid importing bufio/strings in this file ─────

func splitLines(s string) []string {
	var out []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			line := s[start:i]
			if len(line) > 0 && line[len(line)-1] == '\r' {
				line = line[:len(line)-1]
			}
			out = append(out, line)
			start = i + 1
		}
	}
	if start < len(s) {
		out = append(out, s[start:])
	}
	return out
}

func splitFields(s string) []string {
	var out []string
	inField := false
	start := 0
	for i := 0; i <= len(s); i++ {
		isSpace := i == len(s) || s[i] == ' ' || s[i] == '\t'
		if inField && isSpace {
			out = append(out, s[start:i])
			inField = false
		} else if !inField && !isSpace {
			start = i
			inField = true
		}
	}
	return out
}

func trimPrefix(s, prefix string) string {
	if len(s) >= len(prefix) && s[:len(prefix)] == prefix {
		return s[len(prefix):]
	}
	return s
}

func toLower(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'A' && c <= 'Z' {
			b[i] = c + 32
		}
	}
	return string(b)
}
