{{- if .Values.license.content }}
apiVersion: v1
kind: Secret
metadata:
  name: bas-license
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  bas.lic: {{ .Values.license.content | quote }}
{{- end }}
