apiVersion: v1
kind: Secret
metadata:
  name: bas-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  POSTGRES_DSN: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  JWT_SECRET:   "{{ .Values.orchestrator.config.jwtSecret }}"
