// GENERATED by web/tools/split.mjs -- shared mutable state (G1c spec section 5).
export const state = {
  INIT_ATTACH_SELECTED: '',
  _addlSel: {},
  _agtLogTelemetryMetric: '',
  _cmpSel: {},
  _emGroupSel: {},
  _emSweepCurrentId: null,
  _groupSel: {},
  _pwForced: false,
  _tmplGroupSel: {},
  _tmplSelAgents: {},
  _toast: undefined,
  _vexGroupSel: {},
  _vexRunGroupSel: {},
  agents: [],
  scenarioView: 'landing',
  scenarios: [],
};
