package corpusaudit

import (
	"fmt"
	"io"
	"sort"
)

// WriteGeneratedGo writes execclass_generated.go's full source. Only
// StatusClassified items are emitted -- StatusAlreadyHandAuthored items
// are already in execclass.go (emitting them again would be a harmless
// but confusing duplicate map write), and StatusUnresolved items must
// NEVER appear in a committed catalog file.
func WriteGeneratedGo(w io.Writer, items []ClassifiedItem) error {
	type entry struct{ tech, key, class, da, br string }
	var entries []entry
	for _, it := range items {
		if it.Status != StatusClassified {
			continue
		}
		entries = append(entries, entry{it.TechniqueID, it.ActionKey, string(it.Class), it.DestructiveAction, it.BlastRadius})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].tech != entries[j].tech {
			return entries[i].tech < entries[j].tech
		}
		return entries[i].key < entries[j].key
	})

	if _, err := fmt.Fprint(w, "// Code generated by cmd/auditcorpus. DO NOT EDIT.\n"+
		"// Regenerate: go run ./cmd/auditcorpus (needs a local docker compose stack -- see\n"+
		"// packaging/compose/docker-compose.yml's auditcorpus service).\n\n"+
		"package scenario\n\nfunc init() {\n"); err != nil {
		return err
	}
	for _, e := range entries {
		if _, err := fmt.Fprintf(w,
			"\tif executionClassifications[%q] == nil {\n\t\texecutionClassifications[%q] = map[string]*ExecutionClassification{}\n\t}\n"+
				"\texecutionClassifications[%q][%q] = &ExecutionClassification{Class: %q, DestructiveAction: %q, BlastRadius: %q}\n",
			e.tech, e.tech, e.tech, e.key, e.class, e.da, e.br); err != nil {
			return err
		}
	}
	_, err := fmt.Fprint(w, "}\n")
	return err
}

// WriteReportMarkdown writes the coverage report in the exact format the
// design doc specifies, split by source, with real counts from the run
// that produced r -- never hard-coded.
func WriteReportMarkdown(w io.Writer, r CoverageReport) error {
	_, err := fmt.Fprintf(w, "ART:\n"+
		"  discovered: %d\n  reachable: %d\n  classified: %d\n"+
		"  destructive candidates: %d\n  manually reviewed: %d\n  unresolved: %d\n\n"+
		"Caldera:\n"+
		"  discovered: %d\n  reachable: %d\n  classified: %d\n"+
		"  destructive candidates: %d\n  manually reviewed: %d\n  unresolved: %d\n",
		r.ART.Discovered, r.ART.Reachable, r.ART.Classified, r.ART.DestructiveCandidates, r.ART.ManuallyReviewed, r.ART.Unresolved,
		r.Caldera.Discovered, r.Caldera.Reachable, r.Caldera.Classified, r.Caldera.DestructiveCandidates, r.Caldera.ManuallyReviewed, r.Caldera.Unresolved,
	)
	return err
}
