// Code generated by cmd/auditcorpus. DO NOT EDIT.
// Regenerate: go run ./cmd/auditcorpus (needs a local docker compose stack -- see
// packaging/compose/docker-compose.yml's auditcorpus service).

package scenario

func init() {
	if executionClassifications["T1485"] == nil {
		executionClassifications["T1485"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1485"]["overwrite_deleted_data_on_c_drive"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "overwrite_deleted_data_on_c_drive", BlastRadius: "Caldera equivalent of the ART cipher.exe /w:C: test -- identical command semantics, same classification rationale."}
	if executionClassifications["T1485"] == nil {
		executionClassifications["T1485"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1485"]["t1485_test_3_overwrite_deleted_data_on_c_drive"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1485_test_3_overwrite_deleted_data_on_c_drive", BlastRadius: "cipher.exe /w:C: secure-wipes free space on C: -- irreversibly destroys recoverable deleted data across the whole volume; matches T1485 Data Destruction, same family as this catalog's existing T1485 entries."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_10_windows_vssadmin_resize_shadowstorage_volume"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_10_windows_vssadmin_resize_shadowstorage_volume", BlastRadius: "vssadmin resize shadowstorage /For=C: /On=C: /MaxSize=20% shrinks the shadow-storage allocation on C: to 20% -- Windows forcibly discards existing shadow copies that no longer fit, an indirect but real and irreversible VSS-deletion effect, same family as vss_delete."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_1_windows_delete_volume_shadow_copies"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_1_windows_delete_volume_shadow_copies", BlastRadius: "vssadmin.exe delete shadows /all /quiet deletes every VSS shadow copy on the host -- irreversible, removes the ransomware-recovery path. Same effect as this catalog's existing T1490 vss_delete entry."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_2_windows_delete_volume_shadow_copies_via_wmi"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_2_windows_delete_volume_shadow_copies_via_wmi", BlastRadius: "wmic.exe shadowcopy delete deletes all VSS shadow copies via WMI -- same irreversible effect as vssadmin delete shadows, just a different interface to the same destructive action."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_3_windows_wbadmin_delete_windows_backup_catalog"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_3_windows_wbadmin_delete_windows_backup_catalog", BlastRadius: "wbadmin delete catalog -quiet deletes the Windows Server Backup catalog -- irreversible. Same effect as this catalog's existing T1490 wbadmin_delete_catalog entry."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_4_windows_disable_windows_recovery_console_repair"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_4_windows_disable_windows_recovery_console_repair", BlastRadius: "bcdedit /set {default} bootstatuspolicy ignoreallfailures + recoveryenabled no disables Windows Recovery Environment -- removes the final recovery path. Same effect as this catalog's existing T1490 bootloader_recovery_disable entry."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_5_windows_delete_volume_shadow_copies_via_wmi_with_powershell"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_5_windows_delete_volume_shadow_copies_via_wmi_with_powershell", BlastRadius: "Get-WmiObject Win32_Shadowcopy | ForEach-Object {$_.Delete();} deletes all VSS shadow copies via PowerShell/WMI -- same irreversible effect as vssadmin delete shadows, a third interface to the same destructive action."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["t1490_test_7_windows_wbadmin_delete_systemstatebackup"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "t1490_test_7_windows_wbadmin_delete_systemstatebackup", BlastRadius: "wbadmin delete systemstatebackup -keepVersions:0 deletes all Windows system-state backups -- irreversible, removes the OS/registry recovery path, same family as wbadmin_delete_catalog."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_delete_volume_shadow_copies"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_delete_volume_shadow_copies", BlastRadius: "Caldera equivalent of the ART vssadmin delete shadows test -- identical command semantics, same classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_delete_volume_shadow_copies_via_wmi"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_delete_volume_shadow_copies_via_wmi", BlastRadius: "Caldera equivalent of the ART wmic shadowcopy delete test -- identical command semantics, same classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_delete_volume_shadow_copies_via_wmi_with_powershell"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_delete_volume_shadow_copies_via_wmi_with_powershell", BlastRadius: "Caldera equivalent of the ART PowerShell/WMI shadow-copy-delete test -- identical command semantics, same classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_disable_windows_recovery_console_repair"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_disable_windows_recovery_console_repair", BlastRadius: "Caldera equivalent of the ART bcdedit recovery-disable test (combined via && instead of two lines) -- identical command semantics, same classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_vssadmin_resize_shadowstorage_volume"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_vssadmin_resize_shadowstorage_volume", BlastRadius: "Byte-identical command to the ART vssadmin resize shadowstorage test (same hash) -- identical classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_wbadmin_delete_systemstatebackup"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_wbadmin_delete_systemstatebackup", BlastRadius: "Caldera equivalent of the ART wbadmin delete systemstatebackup test -- identical command semantics, same classification rationale."}
	if executionClassifications["T1490"] == nil {
		executionClassifications["T1490"] = map[string]*ExecutionClassification{}
	}
	executionClassifications["T1490"]["windows_wbadmin_delete_windows_backup_catalog"] = &ExecutionClassification{Class: "destructive", DestructiveAction: "windows_wbadmin_delete_windows_backup_catalog", BlastRadius: "Caldera equivalent of the ART wbadmin delete catalog test -- identical command semantics, same classification rationale."}
}
