// Code generated by cmd/auditcorpus. DO NOT EDIT.
// Regenerate: go run ./cmd/auditcorpus (needs a local docker compose stack -- see
// packaging/compose/docker-compose.yml's auditcorpus service).
//
// The generated classification catalog lives in execclass_generated.json and is
// loaded here in init() -- NOT emitted as ~3,450 individual Go string-literal
// assignments as it once was. That earlier form put tens of thousands of string
// literals in one package, which made the release obfuscator (garble -literals)
// rewrite each into its own decryptor and hang the build. The data, the load
// timing (init(), i.e. after the hand-authored var-init snapshot in execclass.go),
// and the resulting executionClassifications catalog are identical to that form,
// so IsHandAuthored and ResolveExecutionClass behave exactly as before.
package scenario

import (
	_ "embed"
	"encoding/json"
)

//go:embed execclass_generated.json
var execclassGeneratedJSON []byte

func init() {
	var entries []struct {
		T string `json:"t"` // technique_id
		A string `json:"a"` // action_key
		C string `json:"c"` // execution class
		D string `json:"d"` // destructive action
		B string `json:"b"` // blast radius
	}
	if err := json.Unmarshal(execclassGeneratedJSON, &entries); err != nil {
		panic("scenario: decoding embedded execution classifications: " + err.Error())
	}
	for _, e := range entries {
		if executionClassifications[e.T] == nil {
			executionClassifications[e.T] = map[string]*ExecutionClassification{}
		}
		executionClassifications[e.T][e.A] = &ExecutionClassification{
			Class:             ExecutionClass(e.C),
			DestructiveAction: e.D,
			BlastRadius:       e.B,
		}
	}
}
