import { state } from './core/state.js';
import { x } from './core/escape.js';
import { stopEvent } from './core/actions.js';
import { closeAdvDrawer, closeAdvRunModal, closeTmplRun, confirmAdversaryRun, confirmTmplRun, loadAdversariesStop, openAdvDrawer, openAdvRunModal, openTmplRun, renderAdvRunWarn, renderAdversaryLibrary, renderTmplGroupSummary, renderTmplOSCompat, setTmplFilter, setTmplTargetMode, tmplGroupChange, tmplRunModeChange, tmplSelAgentChange, toggleAdversarySection } from './features/adversaries.js';
import { closeRemoveAgentModal, closeStopAgentModal, closeUninstallAgentModal, submitRemoveAgent, submitStopAgent, submitUninstallAgent, triggerTicketingSync } from './features/agent-actions.js';
import { closeAgentDetail, closeAgentDetailOnBackdrop, exportCompliance, filterControls, loadAgtLogs, loadAgtLogsTelemetryMetric, loadComplianceReport, openAgentDetail, setAgentState, showAgentTab, toggleEvidence, updateLinuxDownloadCmd } from './features/agent-drawer.js';
import { _apCancelJob, apAssetsClose, apCollectClose, apCollectViewResults, apCountTargets, apDiscoverSubnet, apScheduleClose, approveForLocalUse, approveLocalAckChanged, closeAPAbout, closeApproveLocalModal, closeExposureDetail, closeExposureDetailOnBackdrop, closeGroupPicker, closeScenarioCategoryView, copyRecommendedScenario, copyText, createAgentGroupPrompt, dispatchAPCollect, loadAgents, loadAttackPath, loadCoverageMatrix, loadExecDashboard, loadExposureAssets, loadMoreAgents, loadRecommendations, loadScenarios, manageUsersLink, onAgentSearchInput, openAPAbout, openAPAssets, openAPCollect, openAPSchedule, openAgentGroupMenuStop, openExposureDetail, openModalForScenario, openScenarioCategory, previewScenarioOverlay, renderScenarios, rowMenuAuditPack, rowMenuDetail, rowMenuMoveGroup, rowMenuRemoveAgent, rowMenuReportCsv, rowMenuReportHtml, rowMenuReportJson, rowMenuReportPdf, rowMenuRunSimulation, rowMenuSafeScan, rowMenuStopAgent, rowMenuUninstallAgent, saveAPAsset, saveAPSchedule, scenarioCategoryKeydown, scenarioPinKeydown, scenarioSearchClear, selectAgentGroup, selectDashPref, selectTheme, setAgentFilter, showAgentDownload, showSettingsSection, showThreatPriorityDetail, showThreatPriorityList, submitApproveLocal, submitGroupPicker, toggleDesc, toggleRowMenuById, toggleScenarioPinFromEvent, toggleScenarioSrcGroup, toggleSecret, unpreviewScenarioOverlay } from './features/attack-path.js';
import { auditPage, backupNow, exportAuditLogs, loadAuditLogs, loadBackups, loadLicenseInfo, prepareRestore } from './features/audit-logs.js';
import { closeCampaignDetail, closeCampaignLaunch, cmpAllConfirmChange, cmpOnExistingScenarioChange, cmpOnGroupChange, cmpOnTargetTypeChange, cmpSelChange, cmpSelectAllFiltered, cmpToggleExclusionFromChecked, generateTIScenario, loadCampaigns, loadKEVPack, openCampaignDetail, openCampaignLaunch, openRunFromCampaign, openThreatPriorityActor, pauseCampaign, renderCampaignTargets, resumeCampaign, selectTIPack, setCampaignSource, setCampaignTab, stopCampaign, submitCampaign } from './features/campaigns.js';
import { closeChangePassword, closeChangePasswordOnBackdrop, closeConfirmDiffModal, loadCalderaStatus, openChangePassword, openComplianceDetail, runConfirmDiffModal, submitChangePassword } from './features/compliance.js';
import { loadCoverageAnalytics, openTechnique, renderUTL, setCovView, setUTLFilter } from './features/coverage.js';
import { vfCloseDetail, vfDeleteEvidence, vfLoadQueue, vfPickResult, vfSelect, vfSetDomain, vfSubmit, vfToggleHistory, vfUploadEvidence } from './features/detection-verification.js';
import { _toggleEMExtraScenario, _toggleEMPreviewRow, _toggleVexPreviewRow, _toggleVexPreviewSection, cancelEMSweep, closeEMSweepModal, closeEMSweepModalOnBackdrop, closeEMSweepProgress, closeEMSweepProgressOnBackdrop, closeSweepPreview, closeSweepPreviewOnBackdrop, emGroupSelChange, emRunLayer, emSweepDispatch, loadEmTab, openEMSweepModal, openEMSweepProgress, openEMSweepReport, setEMExtraSearchFromInput, setEMSweepTargetMode, setVexPreviewSearchFromInput, setVexPreviewTacticFromSelect, startSweepFromPreview, stopEMSweep, stopEMSweepCurrent } from './features/endpoint-mastery.js';
import { closeCreateUser, closeCreateUserOnBackdrop, closeDownloadOptions, closeEditUser, closeEditUserOnBackdrop, closeEvidence, closeEvidenceOnBackdrop, confirmRun, copyRaw, doResetPassword, downloadCampaignCSV, downloadCampaignReport, downloadEMSweepReport, downloadRunCSV, downloadRunReport, downloadSweepReport, exportRunJSON, openCampaignReport, openCmdk, openCreateUser, openEditUser, openEvidence, openFindingFromDashboard, openRunReport, pauseRun, resumeRun, stopRun, submitCreateUser, submitEditUser, toggleUserActive } from './features/evidence.js';
import { bulkPushSelectedFindings, loadFindings, loadSLAReport, openFinding, openRemediation, pushFindingToITSM, quickTriageFinding, remBulkTicket, remSingleTicket, revalidateRemediation, setFindingStatus, setFindingTab, toggleAllFindingChecksFromChecked, toggleFindingCheck } from './features/findings.js';
import { closeInitiativeAttachDrawer, closeInitiativeAttachDrawerOnBackdrop, closeInitiativeCreateDrawer, closeInitiativeCreateDrawerOnBackdrop, closeInitiativeDrawer, closeInitiativeDrawerOnBackdrop, initiativeArchiveAction, initiativeAttachSelect, initiativeCloseAction, initiativeDeleteFromMenu, initiativeDetachJob, initiativeRenderAttachList, initiativeSetFilter, loadInitiatives, openInitiativeAttachDrawer, openInitiativeCreateDrawer, openInitiativeDrawer, submitInitiativeAttach, submitInitiativeCreate } from './features/initiatives.js';
import { closeConnectorForm, closeRespondModal, closeResponseConnectorForm, connectorProjectSelectChange, deleteConnector, deleteResponseConnector, fetchConnectorProjects, openAddConnector, openAddResponseConnector, openEditConnector, openEditResponseConnector, openRespondModal, renderConnectorSettings, renderRespondFields, renderResponseConnectorFields, saveConnectorForm, saveResponseConnectorForm, submitRespondAction, testConnectorById, testConnectorForm, testResponseConnectorById } from './features/integrations.js';
import { closeIOCImportModal, closeResults, closeResultsOnBackdrop, loadIOCRegistry, loadIOCRegistryOnEnter, openIOCDetail, openIOCImportModal, setRunIOCSearchFromInput, setRunIOCTypeFilter, submitIOCImport, toggleIOCSuppressed, toggleRunIOCRow } from './features/iocs.js';
import { closeRunLive, closeRunLiveOnBackdrop, closeSweepDrilldown, closeSweepDrilldownOnBackdrop, openRunPanelAction, openSweepDrilldown, openSweepReport, toggleLiveStepAction } from './features/live-run.js';
import { abortExecution, abortExecutionStop, approveExStep, closeExerciseDetail, closeExerciseDetailOnBackdrop, closeOpenAEVDetail, closeOpenAEVDetailOnBackdrop, createPlanFromOpenAEV, launchExercisePrompt, openExerciseDetail, openOpenAEVDetail, removeOpenAEVConfig, saveOpenAEVConfig, syncOpenAEVNow, testOpenAEVConfig, toggleAPHistory } from './features/openaev.js';
import { runRansomwareDrill } from './features/ransomware.js';
import { addStep, addlSelChange, applyPicker, clearSelection, cloneScenario, closeBuilder, closeBuilderOnBackdrop, closeModal, closePicker, closeReportGen, deleteCustomScenario, downloadBuilderYaml, genAgentReport, loadRuns, moveStepBy, openBuilder, openBuilderARTPicker, openBuilderCalderaPicker, openDetailedViewForScenario, openModal, openPicker, openPickerFromModal, openReportGen, pickScenarioUploadFile, pickerSelectAll, pickerToggle, removeStep, renderBuilderMode, renderGroupTargetSummary, renderPickerList, renderRunMode, runGroupChange, saveScenario, selectAllAdditionalAgents, setPF, setTargetMode, submitReport, switchRunTab, techChangeSelection, techCopyId, techKeydown, techOnBlur, techOnInput, techSelectRow, updateVariantDepthNote, uploadScenarioFile, viewRunResults, wizardNav } from './features/reports.js';
import { closeRerunReview, closeRerunReviewOnBackdrop, openCampaignRerunReview, openRerunReview, startRerunFromReview } from './features/rerun-review.js';
import { cancelScheduledAssessment, closeSchedWizard, loadScheduledAssessments, openSchedWizard, openSchedWizardForEdit, schedAuthCheckChange, schedOnModeChange, schedOnRecurrenceChange, schedToggleAgentFromChecked, schedToggleGroupFromChecked, schedWizardNav, submitScheduledAssessment } from './features/scheduled.js';
import { _dismissLicenseGraceBanner, ackAllTamperEvents, doLogin, doLogoutFromMenu, goToProfileFromMenu, licenseBannerDismissHoverOff, licenseBannerDismissHoverOn, openAgentDetailRiskTab, openSettingsFromMenu, setAgentsView, setDashView, showTab, tamperAckHoverOff, tamperAckHoverOn, toggleSidebarCollapsed, toggleUserMenuFromEvent } from './features/shell.js';
import { closeTAXIIConnectorModal, deleteTAXIIConnector, loadARTContentStatus, loadTAXIIConnectors, openTAXIIConnectorModal, removeConnectorConfig, reseedART, saveConnectorConfig, saveTAXIIConnectorForm, simCovHoverOff, simCovHoverOn, syncTAXIIConnectorNow, taxiiToggleAuthFields, testConnectorConfig, testTAXIIConnectorForm, toggleSimCoverage, triggerConnectorSync } from './features/threat-intel.js';
import { loadVariantTab } from './features/variant-executor.js';
import { loadVariantMatrixFromButton } from './features/variant-report.js';
import { _vexCheckAgentSweepConflict, filterVexTechniques, pollVariantRun, renderVexGroupSummary, renderVexRunGroupSummary, runVariants, setVexRunTargetMode, setVexTargetMode, showVexStatHelp, stopVex, stopVexSweep, vexClearAll, vexRunFullSweep, vexRunGroupChange, vexSelectAll, vexSweepGroupChange } from './features/variants.js';

// Called from inline on*= handlers.
export const HANDLER_FUNCTIONS = {
  _apCancelJob,
  _dismissLicenseGraceBanner,
  _toggleEMExtraScenario,
  _toggleEMPreviewRow,
  _toggleVexPreviewRow,
  _toggleVexPreviewSection,
  _vexCheckAgentSweepConflict,
  abortExecution,
  ackAllTamperEvents,
  addStep,
  apCollectClose,
  apCountTargets,
  apDiscoverSubnet,
  applyPicker,
  approveExStep,
  auditPage,
  backupNow,
  bulkPushSelectedFindings,
  cancelEMSweep,
  cancelScheduledAssessment,
  clearSelection,
  cloneScenario,
  closeAPAbout,
  closeAdvDrawer,
  closeAdvRunModal,
  closeAgentDetail,
  closeBuilder,
  closeCampaignDetail,
  closeCampaignLaunch,
  closeChangePassword,
  closeConfirmDiffModal,
  closeConnectorForm,
  closeCreateUser,
  closeDownloadOptions,
  closeEMSweepModal,
  closeEMSweepProgress,
  closeEditUser,
  closeEvidence,
  closeExerciseDetail,
  closeExposureDetail,
  closeGroupPicker,
  closeIOCImportModal,
  closeInitiativeAttachDrawer,
  closeInitiativeCreateDrawer,
  closeInitiativeDrawer,
  closeModal,
  closeOpenAEVDetail,
  closePicker,
  closeRemoveAgentModal,
  closeReportGen,
  closeRerunReview,
  closeRespondModal,
  closeResponseConnectorForm,
  closeResults,
  closeRunLive,
  closeScenarioCategoryView,
  closeSchedWizard,
  closeStopAgentModal,
  closeSweepDrilldown,
  closeSweepPreview,
  closeTAXIIConnectorModal,
  closeTmplRun,
  closeUninstallAgentModal,
  cmpOnExistingScenarioChange,
  cmpOnGroupChange,
  cmpOnTargetTypeChange,
  cmpSelectAllFiltered,
  confirmAdversaryRun,
  confirmRun,
  confirmTmplRun,
  copyRaw,
  copyRecommendedScenario,
  copyText,
  createAgentGroupPrompt,
  createPlanFromOpenAEV,
  deleteConnector,
  deleteCustomScenario,
  deleteResponseConnector,
  deleteTAXIIConnector,
  dispatchAPCollect,
  doLogin,
  doResetPassword,
  downloadBuilderYaml,
  downloadCampaignCSV,
  downloadCampaignReport,
  downloadEMSweepReport,
  downloadRunCSV,
  downloadRunReport,
  downloadSweepReport,
  emRunLayer,
  emSweepDispatch,
  exportAuditLogs,
  exportCompliance,
  exportRunJSON,
  fetchConnectorProjects,
  filterControls,
  filterVexTechniques,
  genAgentReport,
  generateTIScenario,
  initiativeArchiveAction,
  initiativeCloseAction,
  initiativeDetachJob,
  initiativeRenderAttachList,
  initiativeSetFilter,
  launchExercisePrompt,
  loadARTContentStatus,
  loadAgents,
  loadAgtLogs,
  loadAttackPath,
  loadAuditLogs,
  loadBackups,
  loadCalderaStatus,
  loadCampaigns,
  loadComplianceReport,
  loadCoverageAnalytics,
  loadCoverageMatrix,
  loadEmTab,
  loadExecDashboard,
  loadExposureAssets,
  loadFindings,
  loadIOCRegistry,
  loadInitiatives,
  loadKEVPack,
  loadLicenseInfo,
  loadMoreAgents,
  loadRecommendations,
  loadRuns,
  loadSLAReport,
  loadScenarios,
  loadScheduledAssessments,
  loadTAXIIConnectors,
  loadVariantTab,
  onAgentSearchInput,
  openAPAbout,
  openAPAssets,
  openAPCollect,
  openAPSchedule,
  openAddConnector,
  openAddResponseConnector,
  openAdvDrawer,
  openAdvRunModal,
  openAgentDetail,
  openBuilder,
  openBuilderARTPicker,
  openBuilderCalderaPicker,
  openCampaignDetail,
  openCampaignLaunch,
  openCampaignReport,
  openCampaignRerunReview,
  openChangePassword,
  openCmdk,
  openCreateUser,
  openDetailedViewForScenario,
  openEMSweepModal,
  openEMSweepProgress,
  openEditConnector,
  openEditResponseConnector,
  openEditUser,
  openEvidence,
  openExerciseDetail,
  openExposureDetail,
  openFinding,
  openIOCDetail,
  openIOCImportModal,
  openInitiativeAttachDrawer,
  openInitiativeCreateDrawer,
  openInitiativeDrawer,
  openModal,
  openOpenAEVDetail,
  openPicker,
  openPickerFromModal,
  openRemediation,
  openReportGen,
  openRerunReview,
  openRespondModal,
  openRunFromCampaign,
  openRunReport,
  openSchedWizard,
  openSchedWizardForEdit,
  openSweepDrilldown,
  openTAXIIConnectorModal,
  openTechnique,
  openTmplRun,
  pauseCampaign,
  pauseRun,
  pickerSelectAll,
  pickerToggle,
  pollVariantRun,
  prepareRestore,
  pushFindingToITSM,
  quickTriageFinding,
  remBulkTicket,
  remSingleTicket,
  removeConnectorConfig,
  removeOpenAEVConfig,
  removeStep,
  renderAdvRunWarn,
  renderAdversaryLibrary,
  renderBuilderMode,
  renderCampaignTargets,
  renderConnectorSettings,
  renderGroupTargetSummary,
  renderPickerList,
  renderRespondFields,
  renderResponseConnectorFields,
  renderRunMode,
  renderScenarios,
  renderTmplGroupSummary,
  renderTmplOSCompat,
  renderUTL,
  renderVexGroupSummary,
  renderVexRunGroupSummary,
  reseedART,
  resumeCampaign,
  resumeRun,
  revalidateRemediation,
  runConfirmDiffModal,
  runRansomwareDrill,
  runVariants,
  saveAPAsset,
  saveAPSchedule,
  saveConnectorConfig,
  saveConnectorForm,
  saveOpenAEVConfig,
  saveResponseConnectorForm,
  saveScenario,
  saveTAXIIConnectorForm,
  schedOnModeChange,
  schedOnRecurrenceChange,
  schedWizardNav,
  selectAgentGroup,
  selectAllAdditionalAgents,
  selectDashPref,
  selectTIPack,
  selectTheme,
  setAgentFilter,
  setAgentState,
  setAgentsView,
  setCampaignSource,
  setCampaignTab,
  setCovView,
  setDashView,
  setEMSweepTargetMode,
  setFindingStatus,
  setFindingTab,
  setPF,
  setRunIOCTypeFilter,
  setTargetMode,
  setTmplFilter,
  setTmplTargetMode,
  setUTLFilter,
  setVexRunTargetMode,
  setVexTargetMode,
  showAgentDownload,
  showAgentTab,
  showSettingsSection,
  showTab,
  showThreatPriorityDetail,
  showThreatPriorityList,
  showVexStatHelp,
  startRerunFromReview,
  startSweepFromPreview,
  stopCampaign,
  stopEMSweep,
  stopRun,
  stopVex,
  stopVexSweep,
  submitCampaign,
  submitChangePassword,
  submitCreateUser,
  submitEditUser,
  submitGroupPicker,
  submitIOCImport,
  submitInitiativeAttach,
  submitInitiativeCreate,
  submitRemoveAgent,
  submitReport,
  submitRespondAction,
  submitScheduledAssessment,
  submitStopAgent,
  submitUninstallAgent,
  switchRunTab,
  syncOpenAEVNow,
  syncTAXIIConnectorNow,
  taxiiToggleAuthFields,
  techChangeSelection,
  techCopyId,
  techOnBlur,
  techSelectRow,
  testConnectorById,
  testConnectorConfig,
  testConnectorForm,
  testOpenAEVConfig,
  testResponseConnectorById,
  testTAXIIConnectorForm,
  toggleAPHistory,
  toggleAdversarySection,
  toggleEvidence,
  toggleFindingCheck,
  toggleIOCSuppressed,
  toggleRunIOCRow,
  toggleScenarioSrcGroup,
  toggleSecret,
  toggleSidebarCollapsed,
  toggleSimCoverage,
  toggleUserActive,
  triggerConnectorSync,
  triggerTicketingSync,
  unpreviewScenarioOverlay,
  updateLinuxDownloadCmd,
  updateVariantDepthNote,
  uploadScenarioFile,
  vexClearAll,
  vexRunFullSweep,
  vexSelectAll,
  vfCloseDetail,
  vfDeleteEvidence,
  vfLoadQueue,
  vfPickResult,
  vfSelect,
  vfSetDomain,
  vfSubmit,
  vfToggleHistory,
  vfUploadEvidence,
  viewRunResults,
  wizardNav,
  x,
};

// The action registry for data-on-* attributes (G1d). During migration it
// holds every inline-handler function plus the explicit actions below; Task 9
// turns it into the explicit list and deletes HANDLER_FUNCTIONS.
export const ACTIONS = {
  ...HANDLER_FUNCTIONS,
  stopEvent,
  abortExecutionStop,
  addlSelChange,
  approveForLocalUse,
  approveLocalAckChanged,
  closeApproveLocalModal,
  submitApproveLocal,
  apAssetsClose,
  apCollectViewResults,
  apScheduleClose,
  closeAgentDetailOnBackdrop,
  closeBuilderOnBackdrop,
  closeChangePasswordOnBackdrop,
  closeCreateUserOnBackdrop,
  closeEMSweepModalOnBackdrop,
  closeEMSweepProgressOnBackdrop,
  closeEditUserOnBackdrop,
  closeEvidenceOnBackdrop,
  closeExerciseDetailOnBackdrop,
  closeExposureDetailOnBackdrop,
  closeInitiativeAttachDrawerOnBackdrop,
  closeInitiativeCreateDrawerOnBackdrop,
  closeInitiativeDrawerOnBackdrop,
  closeOpenAEVDetailOnBackdrop,
  closeRerunReviewOnBackdrop,
  closeResultsOnBackdrop,
  closeRunLiveOnBackdrop,
  closeSweepDrilldownOnBackdrop,
  closeSweepPreviewOnBackdrop,
  cmpAllConfirmChange,
  cmpSelChange,
  cmpToggleExclusionFromChecked,
  connectorProjectSelectChange,
  doLogoutFromMenu,
  emGroupSelChange,
  goToProfileFromMenu,
  initiativeAttachSelect,
  initiativeDeleteFromMenu,
  licenseBannerDismissHoverOff,
  licenseBannerDismissHoverOn,
  loadAdversariesStop,
  loadAgtLogsTelemetryMetric,
  loadIOCRegistryOnEnter,
  loadVariantMatrixFromButton,
  manageUsersLink,
  moveStepBy,
  openAgentDetailRiskTab,
  openAgentGroupMenuStop,
  openComplianceDetail,
  openEMSweepReport,
  openFindingFromDashboard,
  openModalForScenario,
  openRunPanelAction,
  openScenarioCategory,
  openSettingsFromMenu,
  openSweepReport,
  openThreatPriorityActor,
  pickScenarioUploadFile,
  previewScenarioOverlay,
  rowMenuAuditPack,
  rowMenuDetail,
  rowMenuMoveGroup,
  rowMenuRemoveAgent,
  rowMenuReportCsv,
  rowMenuReportHtml,
  rowMenuReportJson,
  rowMenuReportPdf,
  rowMenuRunSimulation,
  rowMenuSafeScan,
  rowMenuStopAgent,
  rowMenuUninstallAgent,
  runGroupChange,
  scenarioCategoryKeydown,
  scenarioPinKeydown,
  scenarioSearchClear,
  schedAuthCheckChange,
  schedToggleAgentFromChecked,
  schedToggleGroupFromChecked,
  setEMExtraSearchFromInput,
  setRunIOCSearchFromInput,
  setVexPreviewSearchFromInput,
  setVexPreviewTacticFromSelect,
  simCovHoverOff,
  simCovHoverOn,
  stopEMSweepCurrent,
  tamperAckHoverOff,
  tamperAckHoverOn,
  techKeydown,
  techOnInput,
  tmplGroupChange,
  tmplRunModeChange,
  tmplSelAgentChange,
  toggleAllFindingChecksFromChecked,
  toggleDesc,
  toggleLiveStepAction,
  toggleRowMenuById,
  toggleScenarioPinFromEvent,
  toggleUserMenuFromEvent,
  vexRunGroupChange,
  vexSweepGroupChange,
};

// Named only via strings: window[name] lookups and handler names built at runtime
// (e.g. covSegHtml(..., 'setAgentFilter')). Keep this list in sync when adding one.
export const DYNAMIC_HANDLERS = [
  'openAgentDetail',
  'openEMSweepProgress',
  'openSweepDrilldown',
  'renderGroupTargetSummary',
  'renderRunMode',
  'renderTmplGroupSummary',
  'renderTmplOSCompat',
  'renderVexGroupSummary',
  'renderVexRunGroupSummary',
  'setAgentFilter',
  'setCampaignTab',
  'setCovView',
  'setFindingTab',
  'setRunIOCTypeFilter',
  'stopEMSweep',
  'stopVexSweep',
  'x',
];

// Variables read or written by handlers or via window.NAME; backed by state.
export const STATE_GLOBALS = [
  'INIT_ATTACH_SELECTED',
  '_addlSel',
  '_agtLogTelemetryMetric',
  '_cmpSel',
  '_emGroupSel',
  '_emSweepCurrentId',
  '_groupSel',
  '_pwForced',
  '_tmplGroupSel',
  '_tmplSelAgents',
  '_vexGroupSel',
  '_vexRunGroupSel',
  'agents',
  'scenarioView',
  'scenarios',
];

// Assigned as window.NAME = ... in app code (left verbatim).
export const WINDOW_WRITES = [
  '_campaigns',
  '_cmdkBound',
  '_covCounts',
  '_covSt',
  '_covTactics',
  '_evidenceResults',
  '_findings',
  '_rems',
  '_slaReport',
  'onRunEvent',
  'openRunPanel',
  'toggleLiveStep',
];

export function installGlobals() {
  Object.assign(window, HANDLER_FUNCTIONS);
  for (const name of STATE_GLOBALS) {
    Object.defineProperty(window, name, {
      get() { return state[name]; },
      set(v) { state[name] = v; },
      configurable: true,
      enumerable: true,
    });
  }
}
