// GENERATED by web/tools/split.mjs -- entry point: install globals, then run load-time code in original order.
import { installGlobals } from './globals.js';
import { __init_L16159, __init_L16846, __init_L19932, __init_L5162, __init_L5212, __init_L5490, __init_L5494, __init_L8485, __init_L8490, __init_L8723, __init_L8985, __init_L8992 } from './legacy.js';

installGlobals();
__init_L5162();
__init_L5212();
__init_L5490();
__init_L5494();
__init_L8485();
__init_L8490();
__init_L8723();
__init_L8985();
__init_L8992();
__init_L16159();
__init_L16846();
__init_L19932();
