import { ACTIONS } from './globals.js';
import { installActions } from './core/actions.js';
import { installCssVars } from './core/css-vars.js';
import './core/api.js';
import './core/escape.js';
import './core/util.js';
import './features/adversaries.js';
import './features/agent-actions.js';
import './features/agent-drawer.js';
import { __init_L8485, __init_L8490, __init_L8723, __init_L8985, __init_L8992 } from './features/attack-path.js';
import './features/audit-logs.js';
import './features/campaigns.js';
import './features/compliance.js';
import './features/coverage.js';
import './features/detection-verification.js';
import './features/endpoint-mastery.js';
import './features/ad-coverage.js';
import { __init_L16846 } from './features/evidence.js';
import './features/findings.js';
import './features/initiatives.js';
import './features/integrations.js';
import './features/iocs.js';
import { __init_L16159 } from './features/live-run.js';
import './features/openaev.js';
import './features/ransomware.js';
import './features/reports.js';
import './features/rerun-review.js';
import './features/scheduled.js';
import { __init_L19932, __init_L5162, __init_L5212, __init_L5490, __init_L5494 } from './features/shell.js';
import './features/threat-intel.js';
import './features/variant-executor.js';
import './features/variant-report.js';
import './features/variants.js';

installActions(ACTIONS);
installCssVars();
__init_L5162();
__init_L5212();
__init_L5490();
__init_L5494();
__init_L8485();
__init_L8490();
__init_L8723();
__init_L8985();
__init_L8992();
__init_L16159();
__init_L16846();
__init_L19932();
