package config

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
)

// minJWTSecretBytes is the floor HS256 needs for meaningful forgery
// resistance (F4). 32 bytes = 256 bits of key material, matching
// HS256's output size.
const minJWTSecretBytes = 32

// knownWeakJWTSecrets are specific placeholder/example phrases that
// satisfy the length check but must never reach a real deployment --
// the kind of value a human copies from a sample .env and forgets to
// change. Deliberately specific compound phrases, not generic single
// words like "secret" or "password" alone, which would false-positive
// on legitimate random-looking secrets that happen to contain them.
var knownWeakJWTSecrets = []string{
	"changeme", "change-me", "change_me", "changeit", "please-change", "replace-this",
	"your-secret-here", "your-jwt-secret", "example-secret",
	"insecure-default", "dummy-secret", "default-secret",
}

// isKnownWeakSecret reports whether secret is (or contains, case-
// insensitively) one of the known placeholder values -- a substring
// check rather than exact match, since real-world defaults get padded
// to meet a length requirement without changing their actual content
// (e.g. "changeme-changeme-changeme-change").
func isKnownWeakSecret(secret string) bool {
	lower := strings.ToLower(secret)
	for _, weak := range knownWeakJWTSecrets {
		if strings.Contains(lower, weak) {
			return true
		}
	}
	return false
}

type Config struct {
	DatabaseURL string `json:"database_url"`
	// DatabaseAdminURL is the bootstrap/schema-owner connection (bas_user) --
	// used only at startup to run schema DDL and provision bas_app, then
	// closed. Never held by the application past startup. See
	// docs/superpowers/specs/2026-09-30-runtime-role-separation-design.md.
	DatabaseAdminURL string `json:"database_admin_url"`
	// AppDBPassword is bas_app's password (auto-generated by install.sh,
	// never operator-facing). Env: BAS_APP_DB_PASSWORD.
	AppDBPassword     string `json:"-"`
	JWTSecret         string `json:"jwt_secret"`
	AgentSecret       string `json:"agent_secret,omitempty"`
	HTTPPort          int    `json:"http_port"`
	ScenariosDir      string `json:"scenarios_dir"`
	ARTDir            string `json:"art_dir,omitempty"`
	ARTPayloadDir     string `json:"art_payload_dir,omitempty"`     // server-side store of ART external payloads (operator-provided)
	ARTContentVersion string `json:"art_content_version,omitempty"` // content-pack version; reseed is skipped when unchanged
	KEVFile           string `json:"kev_file,omitempty"`            // CISA KEV catalog JSON (baked into image); seeds the cves table
	EPSSFile          string `json:"epss_file,omitempty"`           // FIRST EPSS CSV/CSV.GZ (optional); seeds cve_epss for KEV-linked CVEs
	CalderaURL        string `json:"caldera_url,omitempty"`
	CalderaAPIKey     string `json:"caldera_api_key,omitempty"`
	OTXAPIKey         string `json:"otx_api_key,omitempty"`
	LicensePath       string `json:"license_path,omitempty"`
	AdminPassword     string `json:"admin_password,omitempty"`
	AdminEmail        string `json:"admin_email,omitempty"` // used as the admin username on first-run seed

	// PBKDF2Iterations controls the PBKDF2-HMAC-SHA256 iteration count for
	// password hashing. Minimum enforced at runtime: 310000 (NIST SP 800-132).
	// Set higher for deployments with additional time budget (e.g. 600000).
	PBKDF2Iterations int `json:"pbkdf2_iterations,omitempty"`

	// Exercise Engine — SMTP injector + tracker base URL
	SMTPHost      string `json:"smtp_host,omitempty"`
	SMTPPort      int    `json:"smtp_port,omitempty"`
	SMTPUser      string `json:"smtp_user,omitempty"`
	SMTPPass      string `json:"smtp_pass,omitempty"`
	SMTPFrom      string `json:"smtp_from,omitempty"`
	SMTPFromName  string `json:"smtp_from_name,omitempty"`
	PublicBaseURL string `json:"public_base_url,omitempty"` // e.g. "https://bas.internal" for tracking pixel URLs

	// Exercise Engine — communication injectors (SMS gateway + chat webhooks)
	SMSGatewayURL   string `json:"sms_gateway_url,omitempty"`
	SMSGatewayToken string `json:"sms_gateway_token,omitempty"`
	SMSGatewayFrom  string `json:"sms_gateway_from,omitempty"`
	SlackWebhookURL string `json:"slack_webhook_url,omitempty"`
	TeamsWebhookURL string `json:"teams_webhook_url,omitempty"`

	// Threat-intel connector (MISP / OpenCTI)
	MISPUrl              string   `json:"misp_url,omitempty"`
	MISPApiKey           string   `json:"misp_api_key,omitempty"`
	OpenCTIUrl           string   `json:"opencti_url,omitempty"`
	OpenCTIApiKey        string   `json:"opencti_api_key,omitempty"`
	ThreatIntelPollHours int      `json:"threat_intel_poll_hours,omitempty"` // default 24
	ThreatIntelSectors   []string `json:"threat_intel_sectors,omitempty"`    // e.g. ["financial-services","banking"]
	ThreatIntelRegions   []string `json:"threat_intel_regions,omitempty"`    // e.g. ["Asia","India"]

	// Air-gapped threat-intel: dir holding a signed ti-bundle.json (bundle floor;
	// live MISP/OpenCTI above overlay on top when configured).
	TIBundleDir string `json:"ti_bundle_dir,omitempty"`

	// API rate limiting (opt-in): a single global token-bucket limit protecting
	// against a runaway client, not a per-tenant/commercial quota system (that
	// belongs to the future Audspect Cloud offering, not this on-prem product).
	// Disabled by default so existing installs are never surprise-limited on
	// upgrade.
	// Env: API_RATE_LIMIT_ENABLED=true, API_RATE_LIMIT=1000/min, API_RATE_BURST=200.
	RateLimitEnabled bool `json:"rate_limit_enabled,omitempty"`
	RateLimitPerMin  int  `json:"rate_limit_per_min,omitempty"`
	RateLimitBurst   int  `json:"rate_limit_burst,omitempty"`

	// DNSSinkEnabled controls the DNS-tunneling exfiltration listener
	// (internal/dnssink). Defaults to true -- unlike RateLimitEnabled above,
	// this is a detection-capability feature, not an opt-in safety limit, so
	// it should be on by default; a bind failure (e.g. port 53 already
	// owned) is logged and reflected in the listener's own Status(), never
	// fatal to the rest of the orchestrator, so leaving it enabled by
	// default carries no risk to existing installs. Env: DNS_SINK_ENABLED.
	DNSSinkEnabled bool `json:"dns_sink_enabled,omitempty"`

	// SFTPSinkEnabled controls the SFTP exfiltration listener
	// (internal/sftpsink). Defaults to true for the same reason
	// DNSSinkEnabled does -- a bind failure is logged and reflected in the
	// listener's own Status(), never fatal to the rest of the orchestrator.
	// Env: SFTP_SINK_ENABLED.
	SFTPSinkEnabled bool `json:"sftp_sink_enabled,omitempty"`

	// SMTPSinkEnabled controls the SMTP exfiltration listener
	// (internal/smtpsink). Defaults to true for the same reason
	// DNSSinkEnabled/SFTPSinkEnabled do -- a bind failure is logged and
	// reflected in the listener's own Status(), never fatal to the rest
	// of the orchestrator. Env: SMTP_SINK_ENABLED.
	SMTPSinkEnabled bool `json:"smtp_sink_enabled,omitempty"`

	// MetricsToken, when set, requires "Authorization: Bearer <token>" on
	// GET /metrics. Empty (the default) leaves it open -- same opt-in
	// posture as RateLimitEnabled.
	MetricsToken string `json:"metrics_token,omitempty"`

	// OTLPEndpoint, when set, exports request and span traces to an OTLP/HTTP
	// receiver (Tempo or Jaeger), e.g. http://tempo:4318. Empty disables export.
	OTLPEndpoint string `json:"otlp_endpoint,omitempty"`

	// AlertWebhook, when set, receives a JSON POST for every alert state
	// change (FIRING/RESOLVED). Empty keeps alerts in the in-memory history only.
	AlertWebhook string `json:"alert_webhook,omitempty"`

	// RemoteWriteURL, when set, pushes metrics to a Prometheus remote-write
	// receiver (Prometheus, Mimir, VictoriaMetrics). Empty means no push.
	RemoteWriteURL string `json:"remote_write_url,omitempty"`

	// Agent trust model (B1/B3) — deployment CA + per-agent mTLS.
	// See docs/superpowers/specs/2026-09-27-agent-trust-model-b1-b3-b4-design.md.
	// PKIDir holds the deployment CA's keypair/cert (ca-key.pem, ca-cert.pem),
	// generated on first startup if absent. EnrollHTTPPort serves initial
	// bootstrap CSR submission over TLS with NO client cert required.
	// LegacyHTTPPort is the temporary plaintext listener for pre-migration
	// agents, retired entirely by the separately-scoped B2 work.
	PKIDir string `json:"pki_dir,omitempty"`

	// ServerSANs: comma-separated hostnames/IP addresses (BAS_SERVER_SANS)
	// this orchestrator is reachable at, embedded as Subject Alternative
	// Names on the deployment CA cert (pki.LoadOrGenerateCAWithSANs) --
	// that cert is presented directly as the TLS server identity on every
	// listener, and Go's TLS client verification (no CommonName fallback
	// since Go 1.15) rejects ANY address not listed here. Confirmed live,
	// 2026-09-30: every agent dialing by IP with none set failed with
	// "x509: cannot validate certificate ..., because it doesn't contain
	// any IP SANs" on every single connection attempt. install.sh resolves
	// this the same way it resolves DNS_SINK_BIND_IP; empty is valid (an
	// operator-supplied TLS_CERT/TLS_KEY makes this irrelevant) but means
	// every agent using the self-signed fallback will hit that same error.
	ServerSANs     string `json:"server_sans,omitempty"`
	EnrollHTTPPort int    `json:"enroll_http_port,omitempty"`
	LegacyHTTPPort int    `json:"legacy_http_port,omitempty"`

	// LegacyListenerEnabled (BAS_LEGACY_LISTENER_ENABLED) gates the :9000
	// plaintext legacy listener. Defaults true -- every existing deployment
	// keeps working unchanged. An operator sets this false as Step 3 of the
	// B2 retirement procedure, after GET /api/agents/legacy-migration-status
	// has reported 30 consecutive clean days AND they've reviewed the
	// evidence -- see
	// docs/superpowers/specs/2026-09-30-b2-legacy-transport-retirement-design.md.
	// Reversible: setting it back to true (or unsetting it) and restarting
	// re-enables the listener.
	LegacyListenerEnabled bool `json:"legacy_listener_enabled,omitempty"`

	// CSPMode (BAS_CSP_MODE) selects how the dashboard Content-Security-Policy
	// is sent (G1d): "enforce" (default) or "report-only" -- the escape hatch
	// for a client hitting a violation. There is deliberately no "off"; any
	// other value fails Load.
	CSPMode string `json:"csp_mode,omitempty"`

	// DashboardHTTPPort serves the browser dashboard (StaticHandler + JWT
	// API + /ws/browser) over TLS with NO client-cert requirement --
	// separate from the mTLS agent listener (HTTPPort) so a browser (which
	// has no client certificate) can reach it. See
	// docs/superpowers/specs/2026-09-27-agent-trust-model-deployment-topology-design.md.
	// DashboardTLSCertPath/DashboardTLSKeyPath, if both set, let an operator
	// supply a properly-trusted certificate for this listener instead of
	// the deployment CA's own self-signed one (which browsers show a
	// warning for) -- wires up install.sh's pre-existing BAS_TLS/TLS_CERT/
	// TLS_KEY option, previously dormant (the orchestrator never read it).
	DashboardHTTPPort    int    `json:"dashboard_http_port,omitempty"`
	DashboardTLSCertPath string `json:"dashboard_tls_cert_path,omitempty"`
	DashboardTLSKeyPath  string `json:"dashboard_tls_key_path,omitempty"`
}

// Load reads config from a JSON file, then overrides with environment variables.
// In Kubernetes the file is optional — DATABASE_URL and JWT_SECRET come from Secrets.
func Load(path string) (*Config, error) {
	cfg := &Config{
		// HTTPPort default corrected from 9000 to 9443: LegacyHTTPPort's own
		// default (below) is 9000, so a bare install with no env overrides
		// used to silently produce two colliding listener ports the moment
		// the B1/B3 plan added LegacyHTTPPort -- undetected until this
		// task's collision validation. Every real deployment
		// (docker-compose.yml) already explicitly sets HTTP_PORT=9443, so
		// this only changes the previously-broken bare/no-compose default.
		HTTPPort:              9443,
		ScenariosDir:          "scenarios",
		ARTDir:                "/art-atomics",
		ARTPayloadDir:         "/art-payloads",
		KEVFile:               "/content/cisa-kev.json",
		PBKDF2Iterations:      310000,
		TIBundleDir:           "/intel-bundles",
		RateLimitPerMin:       1000,
		RateLimitBurst:        200,
		DNSSinkEnabled:        true,
		SFTPSinkEnabled:       true,
		SMTPSinkEnabled:       true,
		PKIDir:                "/etc/audspect/pki",
		EnrollHTTPPort:        9444,
		LegacyHTTPPort:        9000,
		DashboardHTTPPort:     9543,
		LegacyListenerEnabled: true,
		CSPMode:               "enforce",
	}

	// Try file first (local dev)
	var jwtFromFile, agentFromFile bool
	if f, err := os.Open(path); err == nil {
		defer f.Close()
		if err := json.NewDecoder(f).Decode(cfg); err != nil {
			return nil, fmt.Errorf("decode config: %w", err)
		}
		// Track which secrets came from the JSON file so we can warn below.
		jwtFromFile = cfg.JWTSecret != ""
		agentFromFile = cfg.AgentSecret != ""
	}

	// Environment variables override file values (Kubernetes / Docker)
	if v := os.Getenv("DATABASE_URL"); v != "" {
		cfg.DatabaseURL = v
	}
	if v := os.Getenv("DATABASE_ADMIN_URL"); v != "" {
		cfg.DatabaseAdminURL = v
	}
	if v := os.Getenv("BAS_APP_DB_PASSWORD"); v != "" {
		cfg.AppDBPassword = v
	}
	if v := os.Getenv("JWT_SECRET"); v != "" {
		cfg.JWTSecret = v
	}
	if v := os.Getenv("HTTP_PORT"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.HTTPPort)
	}
	if v := os.Getenv("SCENARIOS_DIR"); v != "" {
		cfg.ScenariosDir = v
	}
	if v := os.Getenv("ART_DIR"); v != "" {
		cfg.ARTDir = v
	}
	if v := os.Getenv("ART_PAYLOAD_DIR"); v != "" {
		cfg.ARTPayloadDir = v
	}
	if v := os.Getenv("ART_CONTENT_VERSION"); v != "" {
		cfg.ARTContentVersion = v
	}
	if v := os.Getenv("KEV_FILE"); v != "" {
		cfg.KEVFile = v
	}
	if v := os.Getenv("EPSS_FILE"); v != "" {
		cfg.EPSSFile = v
	}
	if v := os.Getenv("CALDERA_URL"); v != "" {
		cfg.CalderaURL = v
	}
	if v := os.Getenv("CALDERA_API_KEY"); v != "" {
		cfg.CalderaAPIKey = v
	}
	if v := os.Getenv("OTX_API_KEY"); v != "" {
		cfg.OTXAPIKey = v
	}
	if v := os.Getenv("AGENT_SECRET"); v != "" {
		cfg.AgentSecret = v
	}
	if v := os.Getenv("SMTP_HOST"); v != "" {
		cfg.SMTPHost = v
	}
	if v := os.Getenv("SMTP_PORT"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.SMTPPort)
	}
	if v := os.Getenv("SMTP_USER"); v != "" {
		cfg.SMTPUser = v
	}
	if v := os.Getenv("SMTP_PASS"); v != "" {
		cfg.SMTPPass = v
	}
	if v := os.Getenv("SMTP_FROM"); v != "" {
		cfg.SMTPFrom = v
	}
	if v := os.Getenv("SMTP_FROM_NAME"); v != "" {
		cfg.SMTPFromName = v
	}
	if v := os.Getenv("PUBLIC_BASE_URL"); v != "" {
		cfg.PublicBaseURL = v
	}
	if v := os.Getenv("SMS_GATEWAY_URL"); v != "" {
		cfg.SMSGatewayURL = v
	}
	if v := os.Getenv("SMS_GATEWAY_TOKEN"); v != "" {
		cfg.SMSGatewayToken = v
	}
	if v := os.Getenv("SMS_GATEWAY_FROM"); v != "" {
		cfg.SMSGatewayFrom = v
	}
	if v := os.Getenv("SLACK_WEBHOOK_URL"); v != "" {
		cfg.SlackWebhookURL = v
	}
	if v := os.Getenv("TEAMS_WEBHOOK_URL"); v != "" {
		cfg.TeamsWebhookURL = v
	}
	if v := os.Getenv("MISP_URL"); v != "" {
		cfg.MISPUrl = v
	}
	if v := os.Getenv("MISP_API_KEY"); v != "" {
		cfg.MISPApiKey = v
	}
	if v := os.Getenv("OPENCTI_URL"); v != "" {
		cfg.OpenCTIUrl = v
	}
	if v := os.Getenv("OPENCTI_API_KEY"); v != "" {
		cfg.OpenCTIApiKey = v
	}
	if v := os.Getenv("THREAT_INTEL_POLL_HOURS"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.ThreatIntelPollHours)
	}
	if v := os.Getenv("TI_BUNDLE_DIR"); v != "" {
		cfg.TIBundleDir = v
	}
	if v := os.Getenv("BAS_LICENSE_PATH"); v != "" {
		cfg.LicensePath = v
	}
	if v := os.Getenv("BAS_ADMIN_PASSWORD"); v != "" {
		cfg.AdminPassword = v
	}
	if v := os.Getenv("BAS_ADMIN_EMAIL"); v != "" {
		cfg.AdminEmail = v
	}
	if v := os.Getenv("BAS_PBKDF2_ITERATIONS"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.PBKDF2Iterations)
	}
	if v := os.Getenv("API_RATE_LIMIT_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			cfg.RateLimitEnabled = b
		}
	}
	if v := os.Getenv("API_RATE_LIMIT"); v != "" {
		fmt.Sscanf(v, "%d/min", &cfg.RateLimitPerMin)
	}
	if v := os.Getenv("API_RATE_BURST"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.RateLimitBurst)
	}
	if v := os.Getenv("DNS_SINK_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			cfg.DNSSinkEnabled = b
		}
	}
	if v := os.Getenv("SFTP_SINK_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			cfg.SFTPSinkEnabled = b
		}
	}
	if v := os.Getenv("SMTP_SINK_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			cfg.SMTPSinkEnabled = b
		}
	}
	if v := os.Getenv("METRICS_TOKEN"); v != "" {
		cfg.MetricsToken = v
	}
	if v := os.Getenv("BAS_OTLP_ENDPOINT"); v != "" {
		cfg.OTLPEndpoint = v
	}
	if v := os.Getenv("BAS_ALERT_WEBHOOK"); v != "" {
		cfg.AlertWebhook = v
	}
	if v := os.Getenv("BAS_REMOTE_WRITE_URL"); v != "" {
		cfg.RemoteWriteURL = v
	}
	if v := os.Getenv("PKI_DIR"); v != "" {
		cfg.PKIDir = v
	}
	if v := os.Getenv("BAS_SERVER_SANS"); v != "" {
		cfg.ServerSANs = v
	}
	if v := os.Getenv("BAS_LEGACY_LISTENER_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			cfg.LegacyListenerEnabled = b
		}
	}
	cspSource := "csp_mode"
	if v := strings.TrimSpace(os.Getenv("BAS_CSP_MODE")); v != "" {
		cfg.CSPMode = v
		cspSource = "BAS_CSP_MODE"
	}
	// Same normalisation for config.json and the env var.
	cfg.CSPMode = strings.ToLower(strings.TrimSpace(cfg.CSPMode))
	if cfg.CSPMode != "enforce" && cfg.CSPMode != "report-only" {
		return nil, fmt.Errorf("%s=%q: must be \"enforce\" or \"report-only\"", cspSource, cfg.CSPMode)
	}
	if v := os.Getenv("HTTP_PORT_ENROLL"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.EnrollHTTPPort)
	}
	if v := os.Getenv("HTTP_PORT_LEGACY"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.LegacyHTTPPort)
	}
	if v := os.Getenv("HTTP_PORT_DASHBOARD"); v != "" {
		fmt.Sscanf(v, "%d", &cfg.DashboardHTTPPort)
	}
	if v := os.Getenv("TLS_CERT"); v != "" {
		cfg.DashboardTLSCertPath = v
	}
	if v := os.Getenv("TLS_KEY"); v != "" {
		cfg.DashboardTLSKeyPath = v
	}

	if cfg.DatabaseURL == "" {
		return nil, fmt.Errorf("database_url required (set DATABASE_URL env var or config file)")
	}
	if cfg.DatabaseAdminURL == "" {
		return nil, fmt.Errorf("database_admin_url required (set DATABASE_ADMIN_URL env var or config file)")
	}
	if cfg.AppDBPassword == "" {
		return nil, fmt.Errorf("bas_app db password required (set BAS_APP_DB_PASSWORD env var)")
	}
	if cfg.JWTSecret == "" {
		return nil, fmt.Errorf("jwt_secret required (set JWT_SECRET env var or config file)")
	}
	// F4: HS256 token-forgery resistance depends entirely on JWT_SECRET's
	// entropy. A present-but-weak secret is as dangerous as a missing one,
	// so fail closed at boot rather than only checking non-empty.
	if len(cfg.JWTSecret) < minJWTSecretBytes {
		return nil, fmt.Errorf("jwt_secret must be at least %d bytes (got %d) -- generate one with "+
			"`openssl rand -base64 32` and set it via JWT_SECRET", minJWTSecretBytes, len(cfg.JWTSecret))
	}
	if isKnownWeakSecret(cfg.JWTSecret) {
		return nil, fmt.Errorf("jwt_secret is a known placeholder/default value -- generate a real secret with " +
			"`openssl rand -base64 32` and set it via JWT_SECRET")
	}

	// ── Security: warn when sensitive secrets live in the JSON file ────────
	// Secrets in config.json are readable by anyone with filesystem access.
	// Best practice: move them to environment variables or a secrets manager.
	if jwtFromFile && os.Getenv("JWT_SECRET") == "" {
		log.Println("[security] WARNING: jwt_secret found in config.json — " +
			"move to JWT_SECRET env var or a secrets manager to harden this deployment")
	}
	if agentFromFile && os.Getenv("AGENT_SECRET") == "" {
		log.Println("[security] WARNING: agent_secret found in config.json — " +
			"move to AGENT_SECRET env var to harden this deployment")
	}

	// Reject colliding listener ports at startup rather than letting two
	// http.Server goroutines race to bind the same port, where the loser's
	// log.Fatalf is much less diagnosable than a clear error naming both
	// values up front.
	ports := map[string]int{
		"HTTP_PORT":           cfg.HTTPPort,
		"HTTP_PORT_ENROLL":    cfg.EnrollHTTPPort,
		"HTTP_PORT_LEGACY":    cfg.LegacyHTTPPort,
		"HTTP_PORT_DASHBOARD": cfg.DashboardHTTPPort,
	}
	seen := make(map[int]string, len(ports))
	for name, port := range ports {
		if other, ok := seen[port]; ok {
			return nil, fmt.Errorf("%s and %s both resolve to port %d -- listener ports must be distinct", other, name, port)
		}
		seen[port] = name
	}

	return cfg, nil
}
